Add unit test of FFT/iFFT
Cidana-Developers/SVT-AV1 pull request #49
Opened 2019-07-25 07:58 UTC by edmond-zhu

add unit test for FFT and iFFT 2D

2019-07-25 09:10 UTC, edmond-zhu commented
# For FFT/iFFT 2d unit test

# Pr for add FFT/iFFT 2d unit test
## license: check if license is ok
## Comments
## warnings in Local build
1. mac: no new warning, only warning: -pie being ignored. It is only used when linking a main executable
2. linux: GNU warning in SpatialFullDistortionTest.cc
3. windows: none

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a. mac: `-pie being ignored. It is only used when linking a main executable`, can be ignored.
  b. linux: SpaticalFullDistoration wanring, could be fixed by merge the latest code;
3. appvedor
  a. no warnings

## dry run output
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = */FFT2DTest.*
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (11 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (36 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (167 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (710 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (2996 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (5 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (19 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (85 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (332 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (1333 ms)
[----------] 10 tests from FFT/FFT2DTest (5708 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (5714 ms total)
[  PASSED  ] 10 tests.
~~~

2019-07-25 09:11 UTC, edmond-zhu commented
@FochQu please help verify it with command:
SvtAv1UnitTests --gtest_filter=*/FFT2DTest.*

2019-07-25 22:48 UTC, Cidana-Developers requested changes

2019-07-25 22:48 UTC, Cidana-Developers commented on test/FFTTest.cc
> +            }
No brace here.

2019-07-25 22:48 UTC, Cidana-Developers commented on test/FFTTest.cc
> +            for (int j = 0; j < data_size; ++j) {
No brace here.

2019-07-25 22:48 UTC, Cidana-Developers commented on test/FFTTest.cc
> +            }
No brace here.

2019-07-26 02:12 UTC, FochQu commented
Branch for add_fft_unit_test
---
+MAC
ld: warning: -pie being ignored. It is only used when linking a main executable
+Linux
no warning
+WIN
no warning

Dry run test
--
Running main() from /home/jenkins/workspace/NightlyCidana-SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = */FFT2DTest.*
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:126: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 5.7425211e-42
  output_ref_[j]
    Which is: 0
txfm_size_: 4 failed at test #0
test input data dump:
0.984657	0.0611642	0.785644	0.460333	
0.605938	0.892446	0.229493	0.722679	
0.619329	0.637642	0.0722722	0.164097	
0.71881	0.748064	0.261739	0.327979	

[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/1, where GetParam() = (0x5569922d5830, 0x5569922a5d40, 0x5569922d5860, 4) (0 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:126: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 2.7088292e+23
  output_ref_[j]
    Which is: 1.7157137e-07
txfm_size_: 8 failed at test #0
test input data dump:
0.984657	0.0611642	0.785644	0.460333	0.605938	0.892446	0.229493	0.722679	
0.619329	0.637642	0.0722722	0.164097	0.71881	0.748064	0.261739	0.327979	
0.421647	0.81937	0.839373	0.228779	0.94612	0.897347	0.95877	0.0555503	
0.570196	0.921458	0.186685	0.227263	0.186474	0.0592936	0.99338	0.749208	
0.289333	0.572431	0.916715	0.506054	0.423637	0.203092	0.520896	0.416202	
0.548069	0.187164	0.378236	0.551747	0.209635	0.529374	0.304063	0.668204	
0.197915	0.727622	0.344258	0.197983	0.721477	0.991387	0.642682	0.258703	
0.380594	0.400878	0.946294	0.69792	0.955872	0.965759	0.239137	0.215028	

[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/2, where GetParam() = (0x5569923860e0, 0x5569922a5d70, 0x556992386170, 8) (0 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:126: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 1.0373291e-08
  output_ref_[j]
    Which is: 2214.3403
txfm_size_: 16 failed at test #0
test input data dump:
0.984657	0.0611642	0.785644	0.460333	0.605938	0.892446	0.229493	0.722679	0.619329	0.637642	0.0722722	0.164097	0.71881	0.748064	0.261739	0.327979	
0.421647	0.81937	0.839373	0.228779	0.94612	0.897347	0.95877	0.0555503	0.570196	0.921458	0.186685	0.227263	0.186474	0.0592936	0.99338	0.749208	
0.289333	0.572431	0.916715	0.506054	0.423637	0.203092	0.520896	0.416202	0.548069	0.187164	0.378236	0.551747	0.209635	0.529374	0.304063	0.668204	
0.197915	0.727622	0.344258	0.197983	0.721477	0.991387	0.642682	0.258703	0.380594	0.400878	0.946294	0.69792	0.955872	0.965759	0.239137	0.215028	
0.516166	0.286828	0.407977	0.92638	0.319963	0.490083	0.0104695	0.272719	0.0881115	0.30337	0.0786786	0.171057	0.399056	0.773859	0.427713	0.342012	
0.974685	0.532012	0.294637	0.230737	0.639167	0.888527	0.71989	0.636416	0.502993	0.767047	0.351788	0.399236	0.0485444	0.286694	0.890402	0.0685135	
0.871032	0.421558	0.0235468	0.188301	0.580282	0.256621	0.63968	0.533514	0.673773	0.0489106	0.453453	0.174273	0.701286	0.443793	0.403213	0.286512	
0.0154869	0.439448	0.81928	0.182087	0.822981	0.567286	0.536355	0.92238	0.151969	0.89327	0.950014	0.554557	0.540308	0.479248	0.228356	0.788742	
0.552553	0.149281	0.217381	0.512212	0.233815	0.410123	0.449539	0.860216	0.290528	0.817241	0.986652	0.16033	0.16679	0.806225	0.728396	0.778794	
0.587596	0.856675	0.668835	0.333202	0.792583	0.257296	0.150124	0.0803692	0.721991	0.105077	0.815396	0.774812	0.328637	0.454693	0.467693	0.355752	
0.594234	0.619529	0.907483	0.239922	0.834187	0.254001	0.562581	0.714568	0.694731	0.477227	0.872543	0.35024	0.729266	0.266202	0.225237	0.875838	
0.506795	0.77493	0.276477	0.287855	0.817536	0.0540732	0.824067	0.184447	0.252385	0.594764	0.406683	0.925502	0.377797	0.284227	0.813931	0.500644	
0.721195	0.0743172	0.288299	0.0834125	0.0410599	0.578932	0.763369	0.667312	0.822021	0.0345762	0.272458	0.989664	0.645406	0.721139	0.912239	0.377675	
0.240233	0.479088	0.333439	0.539919	0.288163	0.690369	0.884518	0.581488	0.207526	0.392178	0.300249	0.824986	0.447938	0.173267	0.555028	0.537542	
0.512044	0.88585	0.201622	0.904624	0.0691493	0.7368	0.864582	0.41528	0.777233	0.448572	0.700928	0.937684	0.878992	0.788416	0.0220828	0.061368	
0.581599	0.82202	0.136743	0.471168	0.0680254	0.319021	0.493293	0.954706	0.544925	0.123637	0.00539269	0.512401	0.78707	0.491307	0.631809	0.101447	

[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/3, where GetParam() = (0x556992386110, 0x5569922a5da0, 0x5569923861b0, 16) (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:126: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 1.0382393e-05
  output_ref_[j]
    Which is: 1.1707646e-19
txfm_size_: 32 failed at test #0
test input data dump:
0.984657	0.0611642	0.785644	0.460333	0.605938	0.892446	0.229493	0.722679	0.619329	0.637642	0.0722722	0.164097	0.71881	0.748064	0.261739	0.327979	0.421647	0.81937	0.839373	0.228779	0.94612	0.897347	0.95877	0.0555503	0.570196	0.921458	0.186685	0.227263	0.186474	0.0592936	0.99338	0.749208	
0.289333	0.572431	0.916715	0.506054	0.423637	0.203092	0.520896	0.416202	0.548069	0.187164	0.378236	0.551747	0.209635	0.529374	0.304063	0.668204	0.197915	0.727622	0.344258	0.197983	0.721477	0.991387	0.642682	0.258703	0.380594	0.400878	0.946294	0.69792	0.955872	0.965759	0.239137	0.215028	
0.516166	0.286828	0.407977	0.92638	0.319963	0.490083	0.0104695	0.272719	0.0881115	0.30337	0.0786786	0.171057	0.399056	0.773859	0.427713	0.342012	0.974685	0.532012	0.294637	0.230737	0.639167	0.888527	0.71989	0.636416	0.502993	0.767047	0.351788	0.399236	0.0485444	0.286694	0.890402	0.0685135	
0.871032	0.421558	0.0235468	0.188301	0.580282	0.256621	0.63968	0.533514	0.673773	0.0489106	0.453453	0.174273	0.701286	0.443793	0.403213	0.286512	0.0154869	0.439448	0.81928	0.182087	0.822981	0.567286	0.536355	0.92238	0.151969	0.89327	0.950014	0.554557	0.540308	0.479248	0.228356	0.788742	
0.552553	0.149281	0.217381	0.512212	0.233815	0.410123	0.449539	0.860216	0.290528	0.817241	0.986652	0.16033	0.16679	0.806225	0.728396	0.778794	0.587596	0.856675	0.668835	0.333202	0.792583	0.257296	0.150124	0.0803692	0.721991	0.105077	0.815396	0.774812	0.328637	0.454693	0.467693	0.355752	
0.594234	0.619529	0.907483	0.239922	0.834187	0.254001	0.562581	0.714568	0.694731	0.477227	0.872543	0.35024	0.729266	0.266202	0.225237	0.875838	0.506795	0.77493	0.276477	0.287855	0.817536	0.0540732	0.824067	0.184447	0.252385	0.594764	0.406683	0.925502	0.377797	0.284227	0.813931	0.500644	
0.721195	0.0743172	0.288299	0.0834125	0.0410599	0.578932	0.763369	0.667312	0.822021	0.0345762	0.272458	0.989664	0.645406	0.721139	0.912239	0.377675	0.240233	0.479088	0.333439	0.539919	0.288163	0.690369	0.884518	0.581488	0.207526	0.392178	0.300249	0.824986	0.447938	0.173267	0.555028	0.537542	
0.512044	0.88585	0.201622	0.904624	0.0691493	0.7368	0.864582	0.41528	0.777233	0.448572	0.700928	0.937684	0.878992	0.788416	0.0220828	0.061368	0.581599	0.82202	0.136743	0.471168	0.0680254	0.319021	0.493293	0.954706	0.544925	0.123637	0.00539269	0.512401	0.78707	0.491307	0.631809	0.101447	
0.289053	0.830023	0.227315	0.443386	0.743053	0.537504	0.0482605	0.320973	0.00241231	0.316662	0.91002	0.551434	0.844699	0.939386	0.808445	0.104014	0.658223	0.164366	0.523744	0.854843	0.579046	0.273807	0.613556	0.650532	0.364004	0.737011	0.891644	0.86836	0.671396	0.306037	0.167128	0.251774	
0.155465	0.369449	0.933943	0.216101	0.276437	0.819913	0.658192	0.430442	0.180504	0.0550106	0.76324	0.310492	0.743075	0.0885448	0.812703	0.703373	0.251424	0.941249	0.916223	0.4781 [...]

2019-07-26 07:37 UTC, edmond-zhu commented on test/FFTTest.cc
> +            }
done

2019-07-26 07:37 UTC, edmond-zhu commented on test/FFTTest.cc
> +            for (int j = 0; j < data_size; ++j) {
done

2019-07-26 07:37 UTC, edmond-zhu commented on test/FFTTest.cc
> +            }
done

2019-07-26 08:40 UTC, edmond-zhu commented
### After checked with the input data from Foch's report; then add them into the failed test:
**1. Windows does not fail on the cases
2. Linux docker 18.04 fails on some of the cases.**

### Please refer to the output log from platforms:

### Windows
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = FFT/*.*
[==========] Running 14 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (10 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (36 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (155 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (681 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (2998 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (6 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (19 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (85 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (337 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (1365 ms)
[----------] 10 tests from FFT/FFT2DTest (5705 ms total)

[----------] 4 tests from FFT/FFT2DFailedTest
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/0
[       OK ] FFT/FFT2DFailedTest.run_failed_cases/0 (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/1
[       OK ] FFT/FFT2DFailedTest.run_failed_cases/1 (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/2
[       OK ] FFT/FFT2DFailedTest.run_failed_cases/2 (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/3
[       OK ] FFT/FFT2DFailedTest.run_failed_cases/3 (1 ms)
[----------] 4 tests from FFT/FFT2DFailedTest (5 ms total)

[----------] Global test environment tear-down
[==========] 14 tests from 2 test cases ran. (5719 ms total)
[  PASSED  ] 14 tests.
~~~

### Linux 18.04 docker
~~~
root@64cd31991505:/av1/Build/linux# ../../Bin/Debug/SvtAv1UnitTests --gtest_filter=FFT/*.*
Running main() from /av1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = FFT/*.*
[==========] Running 14 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (10 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
/av1/test/FFTTest.cc:125: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: -5.7715017e-26
  output_ref_[j]
    Which is: 0
txfm_size_: 4[22] failed at test #0
test data dump:
0.984657,       0.0611642,      0.785644,       0.460333,
0.605938,       0.892446,       0.229493,       0.722679,
0.619329,       0.637642,       0.0722722,      0.164097,
0.71881,        0.748064,       0.261739,       0.327979,

[  FAILED  ] FFT/FFT2DTest.run_fft_accuracy_check/1, where GetParam() = (0x556b955f8a0f, 0x556b9554d27f, 0x556b955f8e7a, 4) (13 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (80 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (291 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (1232 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (4 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (12 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (41 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (161 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (648 ms)
[----------] 10 tests from FFT/FFT2DTest (2492 ms total)

[----------] 4 tests from FFT/FFT2DFailedTest
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/0
/av1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: -5.7715017e-26
  output_ref_[j]
    Which is: 0
txfm_size_: 4[22] failed
test data dump:
0.984657,       0.0611642,      0.785644,       0.460333,
0.605938,       0.892446,       0.229493,       0.722679,
0.619329,       0.637642,       0.0722722,      0.164097,
0.71881,        0.748064,       0.261739,       0.327979,

[  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/0, where GetParam() = (0x556b955f8a0f, 0x556b9554d27f, 4, 0x556b972979c0) (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/1
[       OK ] FFT/FFT2DFailedTest.run_failed_cases/1 (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/2
/av1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 4.8684735
  output_ref_[j]
    Which is: 181.94415
txfm_size_: 16[274] failed
test data dump:
0.984657,       0.0611642,      0.785644,       0.460333,       0.605938,       0.892446,       0.229493,                                                                                                     0.722679,        0.619329,       0.637642,       0.0722722,      0.164097,       0.71881,        0.748064,                                                                                                     0.261739,        0.327979,
0.421647,       0.81937,        0.839373,       0.228779,       0.94612,        0.897347,       0.95877,                                                                                                      0.0555503,       0.570196,       0.921458,       0.186685,       0.227263,       0.186474,       0.0592936,                                                                                                    0.99338, 0.749208,
0.289333,       0.572431,       0.916715,       0.506054,       0.423637,       0.203092,       0.520896,                                                                                                     0.416202,        0.548069,       0.187164,       0.378236,       0.551747,       0.209635,       0.529374,                                                                                                     0.304063,        0.668204,
0.197915,       0.727622,       0.344258,       0.197983,       0.721477,       0.991387,       0.642682,                                                                                                     0.258703,        0.380594,       0.400878,       0.946294,       0.69792,        0.955872,       0.965759,                                                                                                     0.239137,        0.215028,
0.516166,       0.286828,       0.407977,       0.92638,        0.319963,       0.490083,       0.0104695,                                                                                                    0.272719,        0.0881115,      0.30337,        0.0786786,      0.171057,       0.399056,       0.773859,                                                                                                     0.427713,        0.342012,
0.974685,       0.532012,       0.294637,       0.230737,       0.639167,       0.888527,       0.71989,                                                                                                      0.636416,        0.502993,       0.767047,       0.351788,       0.399236,       0.0485444,      0.286694,                                                                                                     0.890402,        0.0685135,
0.871032,       0.421 [...]

2019-07-26 09:54 UTC, FochQu commented
Dry run test (1604vm)
-----
Running main() from /home/jenkins/workspace/NightlyCidana-SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = FFT/*.*
[==========] Running 14 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 10 tests from FFT/FFT2DTest
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (1 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (4 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (15 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (57 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
[       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (233 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (0 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (3 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (9 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (34 ms)
[ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
[       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (135 ms)
[----------] 10 tests from FFT/FFT2DTest (491 ms total)

[----------] 4 tests from FFT/FFT2DFailedTest
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/0
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: -9.0578061e+31
  output_ref_[j]
    Which is: 0.71488607
txfm_size_: 4[22] failed
test data dump:
0.984657,	0.0611642,	0.785644,	0.460333,	
0.605938,	0.892446,	0.229493,	0.722679,	
0.619329,	0.637642,	0.0722722,	0.164097,	
0.71881,	0.748064,	0.261739,	0.327979,	

[  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/0, where GetParam() = (0x5640f33e3120, 0x5640f33b3630, 4, 0x5640f38805a0) (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/1
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 0
  output_ref_[j]
    Which is: 0.98010767
txfm_size_: 8[74] failed
test data dump:
0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,	
0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,	
0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,	
0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,	
0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,	
0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,	
0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,	
0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,	

[  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/1, where GetParam() = (0x5640f34939d0, 0x5640f33b3660, 8, 0x5640f38804a0) (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/2
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 4.0025913e-11
  output_ref_[j]
    Which is: 7.9316165e+34
txfm_size_: 16[274] failed
test data dump:
0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,	0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,	
0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,	0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,	
0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,	0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,	
0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,	0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,	
0.516166,	0.286828,	0.407977,	0.92638,	0.319963,	0.490083,	0.0104695,	0.272719,	0.0881115,	0.30337,	0.0786786,	0.171057,	0.399056,	0.773859,	0.427713,	0.342012,	
0.974685,	0.532012,	0.294637,	0.230737,	0.639167,	0.888527,	0.71989,	0.636416,	0.502993,	0.767047,	0.351788,	0.399236,	0.0485444,	0.286694,	0.890402,	0.0685135,	
0.871032,	0.421558,	0.0235468,	0.188301,	0.580282,	0.256621,	0.63968,	0.533514,	0.673773,	0.0489106,	0.453453,	0.174273,	0.701286,	0.443793,	0.403213,	0.286512,	
0.0154869,	0.439448,	0.81928,	0.182087,	0.822981,	0.567286,	0.536355,	0.92238,	0.151969,	0.89327,	0.950014,	0.554557,	0.540308,	0.479248,	0.228356,	0.788742,	
0.552553,	0.149281,	0.217381,	0.512212,	0.233815,	0.410123,	0.449539,	0.860216,	0.290528,	0.817241,	0.986652,	0.16033,	0.16679,	0.806225,	0.728396,	0.778794,	
0.587596,	0.856675,	0.668835,	0.333202,	0.792583,	0.257296,	0.150124,	0.0803692,	0.721991,	0.105077,	0.815396,	0.774812,	0.328637,	0.454693,	0.467693,	0.355752,	
0.594234,	0.619529,	0.907483,	0.239922,	0.834187,	0.254001,	0.562581,	0.714568,	0.694731,	0.477227,	0.872543,	0.35024,	0.729266,	0.266202,	0.225237,	0.875838,	
0.506795,	0.77493,	0.276477,	0.287855,	0.817536,	0.0540732,	0.824067,	0.184447,	0.252385,	0.594764,	0.406683,	0.925502,	0.377797,	0.284227,	0.813931,	0.500644,	
0.721195,	0.0743172,	0.288299,	0.0834125,	0.0410599,	0.578932,	0.763369,	0.667312,	0.822021,	0.0345762,	0.272458,	0.989664,	0.645406,	0.721139,	0.912239,	0.377675,	
0.240233,	0.479088,	0.333439,	0.539919,	0.288163,	0.690369,	0.884518,	0.581488,	0.207526,	0.392178,	0.300249,	0.824986,	0.447938,	0.173267,	0.555028,	0.537542,	
0.512044,	0.88585,	0.201622,	0.904624,	0.0691493,	0.7368,	0.864582,	0.41528,	0.777233,	0.448572,	0.700928,	0.937684,	0.878992,	0.788416,	0.0220828,	0.061368,	
0.581599,	0.82202,	0.136743,	0.471168,	0.0680254,	0.319021,	0.493293,	0.954706,	0.544925,	0.123637,	0.00539269,	0.512401,	0.78707,	0.491307,	0.631809,	0.101447,	

[  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/2, where GetParam() = (0x5640f3493a00, 0x5640f33b3690, 16, 0x5640f38800a0) (0 ms)
[ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/3
/home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 4.9903121e-10
  output_ref_[j]
    Which is: 4.1725052e-08
txfm_size_: 32[1058] failed
test data dump:
0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,	0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,	0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,	0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,	
0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,	0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,	0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,	0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,	
0.516166,	0.286828,	0.407977,	0.92638,	0.319963,	0.490083,	0.0104695,	0.272719,	0.0881115,	0.30337,	0.0786786,	0.171057,	0.399056,	0.773859,	0.427713,	0.342012,	0.974685,	0.532012,	0.294637,	0.230737,	0.639167,	0.888527,	0.71989,	0.636416,	0.502993,	0.767047,	0.351788,	0.399236,	0.0485444,	0.286694,	0.890402,	0.0685135,	
0.871032,	0.421558,	0.0235468,	0.188301,	0.580282,	0.256621,	0.63968,	0.533514,	0.673773,	0.0489106,	0.453453,	0.174273,	0.701286,	0.443793,	0.403213,	0.286512,	0.0154869,	0.439448,	0.81928,	0.182087,	0.822981,	0.567286,	0.536355,	0.92238,	0.151969,	0.89327,	0.950014,	0.554557,	0.540308,	0.479248,	0.228356,	0.788742,	
0.552553,	0.149281,	0.217381,	0.512212,	0.233815,	0.410123,	0.449539,	0.860216,	0.290528,	0.817241,	0.986652,	0.16033,	0.16679,	0.806225,	0.728396,	0.778794,	0.587596,	0.856675,	0.668835,	0.333202,	0.792583,	0.257296,	0.150124,	0.0803692,	0.721991,	0.105077,	0.815396,	0.774812,	0.328637, [...]

2019-07-26 10:17 UTC, edmond-zhu commented
> Dry run test (1604vm)
> Running main() from /home/jenkins/workspace/NightlyCidana-SVT-AV1/third_party/googletest/src/gtest_main.cc
> Note: Google Test filter = FFT/.
> [==========] Running 14 tests from 2 test cases.
> [----------] Global test environment set-up.
> [----------] 10 tests from FFT/FFT2DTest
> [ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/0
> [       OK ] FFT/FFT2DTest.run_fft_accuracy_check/0 (1 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/1
> [       OK ] FFT/FFT2DTest.run_fft_accuracy_check/1 (4 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/2
> [       OK ] FFT/FFT2DTest.run_fft_accuracy_check/2 (15 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/3
> [       OK ] FFT/FFT2DTest.run_fft_accuracy_check/3 (57 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_accuracy_check/4
> [       OK ] FFT/FFT2DTest.run_fft_accuracy_check/4 (233 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/0
> [       OK ] FFT/FFT2DTest.run_fft_ifft_check/0 (0 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/1
> [       OK ] FFT/FFT2DTest.run_fft_ifft_check/1 (3 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/2
> [       OK ] FFT/FFT2DTest.run_fft_ifft_check/2 (9 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/3
> [       OK ] FFT/FFT2DTest.run_fft_ifft_check/3 (34 ms)
> [ RUN      ] FFT/FFT2DTest.run_fft_ifft_check/4
> [       OK ] FFT/FFT2DTest.run_fft_ifft_check/4 (135 ms)
> [----------] 10 tests from FFT/FFT2DTest (491 ms total)
> [----------] 4 tests from FFT/FFT2DFailedTest
> [ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/0
> /home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
> Expected equality of these values:
> output_tst_[j]
> Which is: -9.0578061e+31
> output_ref_[j]
> Which is: 0.71488607
> txfm_size_: 4[22] failed
> test data dump:
> 0.984657,	0.0611642,	0.785644,	0.460333,
> 0.605938,	0.892446,	0.229493,	0.722679,
> 0.619329,	0.637642,	0.0722722,	0.164097,
> 0.71881,	0.748064,	0.261739,	0.327979,
> [  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/0, where GetParam() = (0x5640f33e3120, 0x5640f33b3630, 4, 0x5640f38805a0) (0 ms)
> [ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/1
> /home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
> Expected equality of these values:
> output_tst_[j]
> Which is: 0
> output_ref_[j]
> Which is: 0.98010767
> txfm_size_: 8[74] failed
> test data dump:
> 0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,
> 0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,
> 0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,
> 0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,
> 0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,
> 0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,
> 0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,
> 0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,
> [  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/1, where GetParam() = (0x5640f34939d0, 0x5640f33b3660, 8, 0x5640f38804a0) (0 ms)
> [ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/2
> /home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
> Expected equality of these values:
> output_tst_[j]
> Which is: 4.0025913e-11
> output_ref_[j]
> Which is: 7.9316165e+34
> txfm_size_: 16[274] failed
> test data dump:
> 0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,	0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,
> 0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,	0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,
> 0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,	0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,
> 0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,	0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,
> 0.516166,	0.286828,	0.407977,	0.92638,	0.319963,	0.490083,	0.0104695,	0.272719,	0.0881115,	0.30337,	0.0786786,	0.171057,	0.399056,	0.773859,	0.427713,	0.342012,
> 0.974685,	0.532012,	0.294637,	0.230737,	0.639167,	0.888527,	0.71989,	0.636416,	0.502993,	0.767047,	0.351788,	0.399236,	0.0485444,	0.286694,	0.890402,	0.0685135,
> 0.871032,	0.421558,	0.0235468,	0.188301,	0.580282,	0.256621,	0.63968,	0.533514,	0.673773,	0.0489106,	0.453453,	0.174273,	0.701286,	0.443793,	0.403213,	0.286512,
> 0.0154869,	0.439448,	0.81928,	0.182087,	0.822981,	0.567286,	0.536355,	0.92238,	0.151969,	0.89327,	0.950014,	0.554557,	0.540308,	0.479248,	0.228356,	0.788742,
> 0.552553,	0.149281,	0.217381,	0.512212,	0.233815,	0.410123,	0.449539,	0.860216,	0.290528,	0.817241,	0.986652,	0.16033,	0.16679,	0.806225,	0.728396,	0.778794,
> 0.587596,	0.856675,	0.668835,	0.333202,	0.792583,	0.257296,	0.150124,	0.0803692,	0.721991,	0.105077,	0.815396,	0.774812,	0.328637,	0.454693,	0.467693,	0.355752,
> 0.594234,	0.619529,	0.907483,	0.239922,	0.834187,	0.254001,	0.562581,	0.714568,	0.694731,	0.477227,	0.872543,	0.35024,	0.729266,	0.266202,	0.225237,	0.875838,
> 0.506795,	0.77493,	0.276477,	0.287855,	0.817536,	0.0540732,	0.824067,	0.184447,	0.252385,	0.594764,	0.406683,	0.925502,	0.377797,	0.284227,	0.813931,	0.500644,
> 0.721195,	0.0743172,	0.288299,	0.0834125,	0.0410599,	0.578932,	0.763369,	0.667312,	0.822021,	0.0345762,	0.272458,	0.989664,	0.645406,	0.721139,	0.912239,	0.377675,
> 0.240233,	0.479088,	0.333439,	0.539919,	0.288163,	0.690369,	0.884518,	0.581488,	0.207526,	0.392178,	0.300249,	0.824986,	0.447938,	0.173267,	0.555028,	0.537542,
> 0.512044,	0.88585,	0.201622,	0.904624,	0.0691493,	0.7368,	0.864582,	0.41528,	0.777233,	0.448572,	0.700928,	0.937684,	0.878992,	0.788416,	0.0220828,	0.061368,
> 0.581599,	0.82202,	0.136743,	0.471168,	0.0680254,	0.319021,	0.493293,	0.954706,	0.544925,	0.123637,	0.00539269,	0.512401,	0.78707,	0.491307,	0.631809,	0.101447,
> [  FAILED  ] FFT/FFT2DFailedTest.run_failed_cases/2, where GetParam() = (0x5640f3493a00, 0x5640f33b3690, 16, 0x5640f38800a0) (0 ms)
> [ RUN      ] FFT/FFT2DFailedTest.run_failed_cases/3
> /home/jenkins/workspace/NightlyCidana-SVT-AV1/test/FFTTest.cc:484: Failure
> Expected equality of these values:
> output_tst_[j]
> Which is: 4.9903121e-10
> output_ref_[j]
> Which is: 4.1725052e-08
> txfm_size_: 32[1058] failed
> test data dump:
> 0.984657,	0.0611642,	0.785644,	0.460333,	0.605938,	0.892446,	0.229493,	0.722679,	0.619329,	0.637642,	0.0722722,	0.164097,	0.71881,	0.748064,	0.261739,	0.327979,	0.421647,	0.81937,	0.839373,	0.228779,	0.94612,	0.897347,	0.95877,	0.0555503,	0.570196,	0.921458,	0.186685,	0.227263,	0.186474,	0.0592936,	0.99338,	0.749208,
> 0.289333,	0.572431,	0.916715,	0.506054,	0.423637,	0.203092,	0.520896,	0.416202,	0.548069,	0.187164,	0.378236,	0.551747,	0.209635,	0.529374,	0.304063,	0.668204,	0.197915,	0.727622,	0.344258,	0.197983,	0.721477,	0.991387,	0.642682,	0.258703,	0.380594,	0.400878,	0.946294,	0.69792,	0.955872,	0.965759,	0.239137,	0.215028,
> 0.516166,	0.286828,	0.407977,	0.92638,	0.319963,	0.490083,	0.0104695,	0.272719,	0.0881115,	0.30337,	0.0786786,	0.171057,	0.399056,	0.773859,	0.427713,	0.342012,	0.974685,	0.532012,	0.294637,	0.230737,	0.639167,	0.888527,	0.71989,	0.636416,	0.502993,	0.767047,	0.351788,	0.399236,	0.0485444,	0.286694,	0.890402,	0.0685135,
> 0.871032,	0.421558,	0.0235468,	0.188301,	0.580282,	0.256621,	0.63968,	0.533514,	0.673773,	0.0489106,	0.453453,	0.174273,	0.701286,	0.443793,	0.403213,	0.286512,	0.0154869,	0.439448,	0.81928,	0.182087,	0.822981,	0.567286,	0.536355,	0.92238,	0.151969,	0.89327,	0.950014,	0.554557,	0.540308,	0.479248,	0.228356,	0.788742,
> 0.552553,	0.149281,	0.217381,	0.512212,	0.233815,	0.410123,	0.449539,	0.860216,	0.290528,	0.817241,	0.986652,	0.16033,	0.16679,	0.806225,	0.728396,	0.778794,	0.587596,	0.856675,	0. [...]

2019-07-26 10:19 UTC, edmond-zhu commented
interesting, foch's tests are all failed, but mine failed 3 of four tests with the same data.

2019-07-29 08:04 UTC, edmond-zhu commented
the mismatch issue of FFT results is caused by the output memory is not set zeros before running the test. we added memory zero in SetUp(), then the issue is fixed. 
@FochQu please help verify it again, thanks!

2019-07-29 09:42 UTC, closed without merging