Fix build issue from min and max
Cidana-Developers/SVT-AV1 pull request #55
Opened 2019-07-30 02:39 UTC by edmond-zhu

remove min and max definition in util.h to fix build issue in docker environment.

2019-08-01 01:50 UTC, Cidana-Developers approved these changes

2019-08-02 02:56 UTC, edmond-zhu commented
### dry run log for quantize unit tests:
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = */QuantizeTest.*
[==========] Running 54 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 54 tests from AVX2/QuantizeTest
[ RUN      ] AVX2/QuantizeTest.ZeroInput/0
[       OK ] AVX2/QuantizeTest.ZeroInput/0 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/1
[       OK ] AVX2/QuantizeTest.ZeroInput/1 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/2
[       OK ] AVX2/QuantizeTest.ZeroInput/2 (1 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/3
[       OK ] AVX2/QuantizeTest.ZeroInput/3 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/4
[       OK ] AVX2/QuantizeTest.ZeroInput/4 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/5
[       OK ] AVX2/QuantizeTest.ZeroInput/5 (1 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/6
[       OK ] AVX2/QuantizeTest.ZeroInput/6 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/7
[       OK ] AVX2/QuantizeTest.ZeroInput/7 (0 ms)
[ RUN      ] AVX2/QuantizeTest.ZeroInput/8
[       OK ] AVX2/QuantizeTest.ZeroInput/8 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/0
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/0 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/1
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/1 (1 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/2
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/2 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/3
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/3 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/4
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/4 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/5
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/5 (1 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/6
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/6 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/7
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/7 (0 ms)
[ RUN      ] AVX2/QuantizeTest.LargeNegativeInput/8
[       OK ] AVX2/QuantizeTest.LargeNegativeInput/8 (1 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/0
[       OK ] AVX2/QuantizeTest.DcOnlyInput/0 (1 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/1
[       OK ] AVX2/QuantizeTest.DcOnlyInput/1 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/2
[       OK ] AVX2/QuantizeTest.DcOnlyInput/2 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/3
[       OK ] AVX2/QuantizeTest.DcOnlyInput/3 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/4
[       OK ] AVX2/QuantizeTest.DcOnlyInput/4 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/5
[       OK ] AVX2/QuantizeTest.DcOnlyInput/5 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/6
[       OK ] AVX2/QuantizeTest.DcOnlyInput/6 (1 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/7
[       OK ] AVX2/QuantizeTest.DcOnlyInput/7 (0 ms)
[ RUN      ] AVX2/QuantizeTest.DcOnlyInput/8
[       OK ] AVX2/QuantizeTest.DcOnlyInput/8 (0 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/0
[       OK ] AVX2/QuantizeTest.RandomInput/0 (48 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/1
[       OK ] AVX2/QuantizeTest.RandomInput/1 (13 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/2
[       OK ] AVX2/QuantizeTest.RandomInput/2 (14 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/3
[       OK ] AVX2/QuantizeTest.RandomInput/3 (49 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/4
[       OK ] AVX2/QuantizeTest.RandomInput/4 (50 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/5
[       OK ] AVX2/QuantizeTest.RandomInput/5 (196 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/6
[       OK ] AVX2/QuantizeTest.RandomInput/6 (94 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/7
[       OK ] AVX2/QuantizeTest.RandomInput/7 (95 ms)
[ RUN      ] AVX2/QuantizeTest.RandomInput/8
[       OK ] AVX2/QuantizeTest.RandomInput/8 (195 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/0
[       OK ] AVX2/QuantizeTest.MultipleQ/0 (12249 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/1
[       OK ] AVX2/QuantizeTest.MultipleQ/1 (3112 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/2
[       OK ] AVX2/QuantizeTest.MultipleQ/2 (3200 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/3
[       OK ] AVX2/QuantizeTest.MultipleQ/3 (12134 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/4
[       OK ] AVX2/QuantizeTest.MultipleQ/4 (12131 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/5
[       OK ] AVX2/QuantizeTest.MultipleQ/5 (48145 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/6
[       OK ] AVX2/QuantizeTest.MultipleQ/6 (24228 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/7
[       OK ] AVX2/QuantizeTest.MultipleQ/7 (24194 ms)
[ RUN      ] AVX2/QuantizeTest.MultipleQ/8
[       OK ] AVX2/QuantizeTest.MultipleQ/8 (48901 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/0
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/0 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/1
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/1 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/2
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/2 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/3
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/3 (1 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/4
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/4 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/5
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/5 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/6
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/6 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/7
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/7 (0 ms)
[ RUN      ] AVX2/QuantizeTest.CoeffHalfDequant/8
[       OK ] AVX2/QuantizeTest.CoeffHalfDequant/8 (0 ms)
[----------] 54 tests from AVX2/QuantizeTest (189132 ms total)

[----------] Global test environment tear-down
[==========] 54 tests from 1 test case ran. (189139 ms total)
[  PASSED  ] 54 tests.

  YOU HAVE 9 DISABLED TESTS
~~~

2019-08-02 08:22 UTC, Cidana-Developers requested changes

2019-08-02 08:22 UTC, Cidana-Developers commented on test/random.h
> + * (-2^31,2^31).
Should be [-2^31, 2^31)?

2019-08-02 08:24 UTC, Cidana-Developers commented
Since this CL related to FwdTxfmTest and SelfGuidedTest, should dry-run them too.

2019-08-02 09:19 UTC, edmond-zhu commented on test/random.h
> + * (-2^31,2^31).
its done

2019-08-02 09:23 UTC, Cidana-Developers commented on test/random.h
> + * (-2^31,2^31).
Not changed.

2019-08-02 09:29 UTC, edmond-zhu commented
Dry run for self-guarded test : 

SvtAv1UnitTests --gtest_filter=RST/*.*
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = RST/*.*
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from RST/PixelProjErrorLbdTest
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithRandomValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithRandomValue/0 (4209 ms)
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithRandomSizeAndValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithRandomSizeAndValue/0 (4201 ms)
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithExtremeValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithExtremeValue/0 (435 ms)
[----------] 3 tests from RST/PixelProjErrorLbdTest (8849 ms total)

[----------] 3 tests from RST/PixelProjErrorHbdTest
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithRandomValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithRandomValue/0 (4235 ms)
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithRandomSizeAndValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithRandomSizeAndValue/0 (4186 ms)
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithExtremeValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithExtremeValue/0 (428 ms)
[----------] 3 tests from RST/PixelProjErrorHbdTest (8853 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (17710 ms total)
[  PASSED  ] 6 tests.
~~~

SvtAv1UnitTests --gtest_filter=SelfGuidedToolsTest.*
~~~

~~~

2019-08-02 09:32 UTC, Cidana-Developers approved these changes

2019-08-02 09:40 UTC, edmond-zhu commented
dry run for transform unit test:
~~~
SvtAv1UnitTests --gtest_filter=TX/*.*
~~~
~~~
Running main() from C:\Works\AV1\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = TX/*.*
[==========] Running 123 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from TX/AV1FwdTxfm1dTest
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/0
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/0 (12 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/1
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/1 (19 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/2
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/2 (57 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/3
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/3 (190 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/4
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/4 (670 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/5
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/5 (6 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/6
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/6 (20 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/7
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/7 (60 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/8
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/8 (6 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/9
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/9 (9 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/10
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/10 (21 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/11
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/11 (37 ms)
[----------] 12 tests from TX/AV1FwdTxfm1dTest (1119 ms total)

[----------] 38 tests from TX/FwdTxfm2dAsmTest
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/0
[       OK ] TX/FwdTxfm2dAsmTest.match_test/0 (8 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/1
[       OK ] TX/FwdTxfm2dAsmTest.match_test/1 (7 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/2
[       OK ] TX/FwdTxfm2dAsmTest.match_test/2 (32 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/3
[       OK ] TX/FwdTxfm2dAsmTest.match_test/3 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/4
[       OK ] TX/FwdTxfm2dAsmTest.match_test/4 (134 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/5
[       OK ] TX/FwdTxfm2dAsmTest.match_test/5 (133 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/6
[       OK ] TX/FwdTxfm2dAsmTest.match_test/6 (59 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/7
[       OK ] TX/FwdTxfm2dAsmTest.match_test/7 (61 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/8
[       OK ] TX/FwdTxfm2dAsmTest.match_test/8 (149 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/9
[       OK ] TX/FwdTxfm2dAsmTest.match_test/9 (149 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/10
[       OK ] TX/FwdTxfm2dAsmTest.match_test/10 (18 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/11
[       OK ] TX/FwdTxfm2dAsmTest.match_test/11 (17 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/12
[       OK ] TX/FwdTxfm2dAsmTest.match_test/12 (16 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/13
[       OK ] TX/FwdTxfm2dAsmTest.match_test/13 (17 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/14
[       OK ] TX/FwdTxfm2dAsmTest.match_test/14 (68 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/15
[       OK ] TX/FwdTxfm2dAsmTest.match_test/15 (69 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/16
[       OK ] TX/FwdTxfm2dAsmTest.match_test/16 (68 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/17
[       OK ] TX/FwdTxfm2dAsmTest.match_test/17 (68 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/18
[       OK ] TX/FwdTxfm2dAsmTest.match_test/18 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/19
[       OK ] TX/FwdTxfm2dAsmTest.match_test/19 (33 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/20
[       OK ] TX/FwdTxfm2dAsmTest.match_test/20 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/21
[       OK ] TX/FwdTxfm2dAsmTest.match_test/21 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/22
[       OK ] TX/FwdTxfm2dAsmTest.match_test/22 (75 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/23
[       OK ] TX/FwdTxfm2dAsmTest.match_test/23 (74 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/24
[       OK ] TX/FwdTxfm2dAsmTest.match_test/24 (74 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/25
[       OK ] TX/FwdTxfm2dAsmTest.match_test/25 (73 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/26
[       OK ] TX/FwdTxfm2dAsmTest.match_test/26 (32 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/27
[       OK ] TX/FwdTxfm2dAsmTest.match_test/27 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/28
[       OK ] TX/FwdTxfm2dAsmTest.match_test/28 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/29
[       OK ] TX/FwdTxfm2dAsmTest.match_test/29 (31 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/30
[       OK ] TX/FwdTxfm2dAsmTest.match_test/30 (14 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/31
[       OK ] TX/FwdTxfm2dAsmTest.match_test/31 (14 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/32
[       OK ] TX/FwdTxfm2dAsmTest.match_test/32 (15 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/33
[       OK ] TX/FwdTxfm2dAsmTest.match_test/33 (14 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/34
[       OK ] TX/FwdTxfm2dAsmTest.match_test/34 (35 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/35
[       OK ] TX/FwdTxfm2dAsmTest.match_test/35 (34 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/36
[       OK ] TX/FwdTxfm2dAsmTest.match_test/36 (34 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/37
[       OK ] TX/FwdTxfm2dAsmTest.match_test/37 (35 ms)
[----------] 38 tests from TX/FwdTxfm2dAsmTest (1905 ms total)

[----------] 51 tests from TX/AV1FwdTxfm2dTest
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/0
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/0 (8 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/1
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/1 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/2
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/2 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/3
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/3 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/4
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/4 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/5
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/5 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/6
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/6 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/7
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/7 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/8
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/8 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/9
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/9 (5 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/10
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/10 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/11
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/11 (7 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/12
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/12 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/13
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/13 (5 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/14
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/14 (5 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/15
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/15 (6 ms)
[ RUN      ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy_check/16
[       OK ] TX/AV1FwdTxfm2dTest.run_fwd_accuracy [...]

2019-08-05 05:54 UTC, Cidana-Developers commented
@FochQu Please help to verify this.

2019-08-05 10:15 UTC, FochQu approved these changes
Branch for fix_min_max_build_issue
+Mac：
ld: warning: -pie being ignored. It is only used when linking a main executable
+Linux：
no warning
+Windows
no warning

Dry run test
--
~~~
jenkins@jenkins-agent:~/test/SVT-AV1/Bin/Release$ ./SvtAv1UnitTests --gtest_filter=RST/*.*
Running main() from /home/jenkins/test/SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = RST/*.*
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from RST/PixelProjErrorLbdTest
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithRandomValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithRandomValue/0 (727 ms)
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithRandomSizeAndValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithRandomSizeAndValue/0 (725 ms)
[ RUN      ] RST/PixelProjErrorLbdTest.MatchTestWithExtremeValue/0
[       OK ] RST/PixelProjErrorLbdTest.MatchTestWithExtremeValue/0 (75 ms)
[----------] 3 tests from RST/PixelProjErrorLbdTest (1527 ms total)

[----------] 3 tests from RST/PixelProjErrorHbdTest
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithRandomValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithRandomValue/0 (736 ms)
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithRandomSizeAndValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithRandomSizeAndValue/0 (727 ms)
[ RUN      ] RST/PixelProjErrorHbdTest.MatchTestWithExtremeValue/0
[       OK ] RST/PixelProjErrorHbdTest.MatchTestWithExtremeValue/0 (74 ms)
[----------] 3 tests from RST/PixelProjErrorHbdTest (1537 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (3064 ms total)
[  PASSED  ] 6 tests.

jenkins@jenkins-agent:~/test/SVT-AV1/Bin/Release$ ./SvtAv1UnitTests --gtest_filter=SelfGuidedToolsTest.*
Running main() from /home/jenkins/test/SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = SelfGuidedToolsTest.*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SelfGuidedToolsTest
[ RUN      ] SelfGuidedToolsTest.GetProjSubspaceMatchTest
[       OK ] SelfGuidedToolsTest.GetProjSubspaceMatchTest (31631 ms)
[----------] 1 test from SelfGuidedToolsTest (31631 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (31631 ms total)
[  PASSED  ] 1 test.

jenkins@jenkins-agent:~/test/SVT-AV1/Bin/Release$ ./SvtAv1UnitTests --gtest_filt                                                                                                                               er=TX/*.*
Running main() from /home/jenkins/test/SVT-AV1/third_party/googletest/src/gtest_                                                                                                                               main.cc
Note: Google Test filter = TX/*.*
[==========] Running 123 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 12 tests from TX/AV1FwdTxfm1dTest
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/0
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/0 (2 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/1
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/1 (9 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/2
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/2 (35 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/3
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/3 (155 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/4
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/4 (859 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/5
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/5 (1 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/6
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/6 (9 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/7
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/7 (34 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/8
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/8 (1 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/9
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/9 (1 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/10
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/10 (3 ms)
[ RUN      ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/11
[       OK ] TX/AV1FwdTxfm1dTest.run_fwd_accuracy_check/11 (5 ms)
[----------] 12 tests from TX/AV1FwdTxfm1dTest (1115 ms total)

[----------] 38 tests from TX/FwdTxfm2dAsmTest
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/0
[       OK ] TX/FwdTxfm2dAsmTest.match_test/0 (1 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/1
[       OK ] TX/FwdTxfm2dAsmTest.match_test/1 (1 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/2
[       OK ] TX/FwdTxfm2dAsmTest.match_test/2 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/3
[       OK ] TX/FwdTxfm2dAsmTest.match_test/3 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/4
[       OK ] TX/FwdTxfm2dAsmTest.match_test/4 (19 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/5
[       OK ] TX/FwdTxfm2dAsmTest.match_test/5 (18 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/6
[       OK ] TX/FwdTxfm2dAsmTest.match_test/6 (8 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/7
[       OK ] TX/FwdTxfm2dAsmTest.match_test/7 (9 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/8
[       OK ] TX/FwdTxfm2dAsmTest.match_test/8 (21 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/9
[       OK ] TX/FwdTxfm2dAsmTest.match_test/9 (20 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/10
[       OK ] TX/FwdTxfm2dAsmTest.match_test/10 (3 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/11
[       OK ] TX/FwdTxfm2dAsmTest.match_test/11 (2 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/12
[       OK ] TX/FwdTxfm2dAsmTest.match_test/12 (2 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/13
[       OK ] TX/FwdTxfm2dAsmTest.match_test/13 (3 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/14
[       OK ] TX/FwdTxfm2dAsmTest.match_test/14 (9 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/15
[       OK ] TX/FwdTxfm2dAsmTest.match_test/15 (8 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/16
[       OK ] TX/FwdTxfm2dAsmTest.match_test/16 (9 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/17
[       OK ] TX/FwdTxfm2dAsmTest.match_test/17 (9 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/18
[       OK ] TX/FwdTxfm2dAsmTest.match_test/18 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/19
[       OK ] TX/FwdTxfm2dAsmTest.match_test/19 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/20
[       OK ] TX/FwdTxfm2dAsmTest.match_test/20 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/21
[       OK ] TX/FwdTxfm2dAsmTest.match_test/21 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/22
[       OK ] TX/FwdTxfm2dAsmTest.match_test/22 (10 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/23
[       OK ] TX/FwdTxfm2dAsmTest.match_test/23 (10 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/24
[       OK ] TX/FwdTxfm2dAsmTest.match_test/24 (10 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/25
[       OK ] TX/FwdTxfm2dAsmTest.match_test/25 (11 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/26
[       OK ] TX/FwdTxfm2dAsmTest.match_test/26 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/27
[       OK ] TX/FwdTxfm2dAsmTest.match_test/27 (4 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/28
[       OK ] TX/FwdTxfm2dAsmTest.match_test/28 (5 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/29
[       OK ] TX/FwdTxfm2dAsmTest.match_test/29 (5 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/30
[       OK ] TX/FwdTxfm2dAsmTest.match_test/30 (2 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/31
[       OK ] TX/FwdTxfm2dAsmTest.match_test/31 (2 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_test/32
[       OK ] TX/FwdTxfm2dAsmTest.match_test/32 (2 ms)
[ RUN      ] TX/FwdTxfm2dAsmTest.match_tes [...]

2019-08-06 00:27 UTC, Cidana-Developers commented
Already merged, close it.

2019-08-06 00:27 UTC, closed without merging