Add residual test
Cidana-Developers/SVT-AV1 pull request #68
Opened 2019-08-27 02:39 UTC by ivy-zhang

1.add ResidualKernel_avx2 test
2.add residual_kernel16bit_sse2_intrin test
3.add residual_kernel_sub_sampled{w}x{h}_sse_intrin test
4.add sum_residual8bit_avx2_intrin test

2019-08-27 02:41 UTC, ivy-zhang commented
# Add Residual test

## Comments
## warnings in Local build
1. linux:  ok
2. windows:  ok

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a.  linux: ok
3. appvedor
  a. no warnings

## Test Plan: 
  Run the unit test with `./SvtAv1UnitTest --gtest_filter="*Residual*"`, and check the result

## dry run output
~~~
$ ./SvtAv1UnitTests.exe --gtest_filter="*Residual*"
Running main() from C:\Users\Ryan\adR\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = *Residual*
[==========] Running 162 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 132 tests from Residual/ResidualTest
[ RUN      ] Residual/ResidualTest.ResidualTest/0
[       OK ] Residual/ResidualTest.ResidualTest/0 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/1
[       OK ] Residual/ResidualTest.ResidualTest/1 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/2
[       OK ] Residual/ResidualTest.ResidualTest/2 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/3
[       OK ] Residual/ResidualTest.ResidualTest/3 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/4
[       OK ] Residual/ResidualTest.ResidualTest/4 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/5
[       OK ] Residual/ResidualTest.ResidualTest/5 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/6
[       OK ] Residual/ResidualTest.ResidualTest/6 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/7
[       OK ] Residual/ResidualTest.ResidualTest/7 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/8
[       OK ] Residual/ResidualTest.ResidualTest/8 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/9
[       OK ] Residual/ResidualTest.ResidualTest/9 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/10
[       OK ] Residual/ResidualTest.ResidualTest/10 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/11
[       OK ] Residual/ResidualTest.ResidualTest/11 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/12
[       OK ] Residual/ResidualTest.ResidualTest/12 (1 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/13
[       OK ] Residual/ResidualTest.ResidualTest/13 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/14
[       OK ] Residual/ResidualTest.ResidualTest/14 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/15
[       OK ] Residual/ResidualTest.ResidualTest/15 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/16
[       OK ] Residual/ResidualTest.ResidualTest/16 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/17
[       OK ] Residual/ResidualTest.ResidualTest/17 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/18
[       OK ] Residual/ResidualTest.ResidualTest/18 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/19
[       OK ] Residual/ResidualTest.ResidualTest/19 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/20
[       OK ] Residual/ResidualTest.ResidualTest/20 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/21
[       OK ] Residual/ResidualTest.ResidualTest/21 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/22
[       OK ] Residual/ResidualTest.ResidualTest/22 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/23
[       OK ] Residual/ResidualTest.ResidualTest/23 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/24
[       OK ] Residual/ResidualTest.ResidualTest/24 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/25
[       OK ] Residual/ResidualTest.ResidualTest/25 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/26
[       OK ] Residual/ResidualTest.ResidualTest/26 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/27
[       OK ] Residual/ResidualTest.ResidualTest/27 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/28
[       OK ] Residual/ResidualTest.ResidualTest/28 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/29
[       OK ] Residual/ResidualTest.ResidualTest/29 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/30
[       OK ] Residual/ResidualTest.ResidualTest/30 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/31
[       OK ] Residual/ResidualTest.ResidualTest/31 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/32
[       OK ] Residual/ResidualTest.ResidualTest/32 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/33
[       OK ] Residual/ResidualTest.ResidualTest/33 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/34
[       OK ] Residual/ResidualTest.ResidualTest/34 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/35
[       OK ] Residual/ResidualTest.ResidualTest/35 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/36
[       OK ] Residual/ResidualTest.ResidualTest/36 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/37
[       OK ] Residual/ResidualTest.ResidualTest/37 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/38
[       OK ] Residual/ResidualTest.ResidualTest/38 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/39
[       OK ] Residual/ResidualTest.ResidualTest/39 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/40
[       OK ] Residual/ResidualTest.ResidualTest/40 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/41
[       OK ] Residual/ResidualTest.ResidualTest/41 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/42
[       OK ] Residual/ResidualTest.ResidualTest/42 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/43
[       OK ] Residual/ResidualTest.ResidualTest/43 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/44
[       OK ] Residual/ResidualTest.ResidualTest/44 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/45
[       OK ] Residual/ResidualTest.ResidualTest/45 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/46
[       OK ] Residual/ResidualTest.ResidualTest/46 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/47
[       OK ] Residual/ResidualTest.ResidualTest/47 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/48
[       OK ] Residual/ResidualTest.ResidualTest/48 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/49
[       OK ] Residual/ResidualTest.ResidualTest/49 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/50
[       OK ] Residual/ResidualTest.ResidualTest/50 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/51
[       OK ] Residual/ResidualTest.ResidualTest/51 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/52
[       OK ] Residual/ResidualTest.ResidualTest/52 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/53
[       OK ] Residual/ResidualTest.ResidualTest/53 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/54
[       OK ] Residual/ResidualTest.ResidualTest/54 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/55
[       OK ] Residual/ResidualTest.ResidualTest/55 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/56
[       OK ] Residual/ResidualTest.ResidualTest/56 (2 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/57
[       OK ] Residual/ResidualTest.ResidualTest/57 (1 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/58
[       OK ] Residual/ResidualTest.ResidualTest/58 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/59
[       OK ] Residual/ResidualTest.ResidualTest/59 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/60
[       OK ] Residual/ResidualTest.ResidualTest/60 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/61
[       OK ] Residual/ResidualTest.ResidualTest/61 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/62
[       OK ] Residual/ResidualTest.ResidualTest/62 (3 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/63
[       OK ] Residual/ResidualTest.ResidualTest/63 (1 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/64
[       OK ] Residual/ResidualTest.ResidualTest/64 (0 ms)
[ RUN      ] Residual/ResidualTest.ResidualTest/65
[       OK ] Residual/ResidualTest.ResidualTest/65 (3 ms)
[ RUN      ] Residual/ResidualTest.Residual16bitTest/0
[       OK ] Residual/ResidualTest.Residual16bitTest/0 (0 ms)
[ RUN      ] Residual/ResidualTest.Residual [...]

2019-08-27 05:49 UTC, Cidana-Developers commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-27 06:45 UTC, Cidana-Developers requested changes

2019-08-27 06:45 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +#include "aom_dsp_rtcd.h "
Additional space after aom_dsp_rtcd.h, please fix it.

2019-08-27 06:45 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +            for (int i = 0; i < test_size_; i++) {
GNU warnings: warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]

2019-08-27 06:45 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +            for (int i = 0; i < test_size_; i++) {
warning: comparison of integers of different signs: 'int' and 'uint32_t' (aka 'unsigned int') [-Wsign-compare]

2019-08-27 07:01 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=Residual

2019-08-27 07:09 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=Residual

2019-08-27 07:17 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-27 07:28 UTC, edmond-zhu commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=\*Residual\*

2019-08-27 07:41 UTC, FochQu commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-27 07:55 UTC, FochQu commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 01:44 UTC, Cidana-Developers commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 05:22 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 05:27 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-30 05:30 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 05:38 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Residual</em><br />
[==========] Running 162 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 132 tests from ResidualKernel/ResidualTest<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/0<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/0 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/1<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/1 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/2<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/2 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/3<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/3 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/4<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/4 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/5<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/5 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/6<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/6 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/7<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/7 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/8<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/8 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/9<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/9 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/10<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/10 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/11<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/11 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/12<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/12 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/13<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/13 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/14<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/14 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/15<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/15 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/16<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/16 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/17<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/17 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/18<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/18 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/19<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/19 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/20<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/20 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/21<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/21 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/22<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/22 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/23<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/23 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/24<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/24 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/25<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/25 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/26<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/26 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/27<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/27 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/28<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/28 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/29<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/29 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/30<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/30 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/31<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/31 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/32<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/32 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/33<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/33 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/34<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/34 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/35<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/35 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/36<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/36 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/37<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/37 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/38<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/38 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/39<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/39 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/40<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/40 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/41<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/41 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/42<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/42 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/43<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/43 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/44<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/44 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/45<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/45 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/46<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/46 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/47<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/47 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/48<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/48 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/49<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/49 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/50<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/50 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/51<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/51 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/52<br / [...]

2019-08-30 06:10 UTC, Cidana-Developers requested changes

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +SubSampledParam subsampledParam[] = {
Use CamelCase for types and under_score for variable names (TypeName my_instance;)

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +        residual1_aligned_ = (int16_t *)eb_aom_memalign(16, 2 * test_size_);
can we declare the buffer without _aligned_ suffix?

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +        for (uint16_t j = 0; j < height; j++) {
using uint32_t instead of uint16_t

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +        const int16_t mask = (1 << 8) - 1;
since its 16bit, should the mask be (1 << 16) - 1?

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +            for (uint32_t i = 0; i < MAX_SB_SQUARE; i++)
using eb_buffer_random()?

2019-08-30 06:10 UTC, Cidana-Developers commented on test/ResidualTest.cc
> +        int32_t sumBlock1, sumBlock2;
sum_block1, sum_block2.

2019-08-30 06:43 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 06:45 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-30 06:51 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Residual</em><br />
[==========] Running 162 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 132 tests from ResidualKernel/ResidualTest<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/0<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/0 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/1<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/1 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/2<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/2 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/3<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/3 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/4<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/4 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/5<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/5 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/6<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/6 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/7<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/7 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/8<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/8 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/9<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/9 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/10<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/10 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/11<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/11 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/12<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/12 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/13<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/13 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/14<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/14 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/15<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/15 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/16<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/16 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/17<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/17 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/18<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/18 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/19<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/19 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/20<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/20 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/21<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/21 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/22<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/22 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/23<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/23 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/24<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/24 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/25<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/25 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/26<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/26 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/27<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/27 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/28<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/28 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/29<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/29 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/30<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/30 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/31<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/31 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/32<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/32 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/33<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/33 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/34<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/34 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/35<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/35 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/36<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/36 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/37<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/37 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/38<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/38 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/39<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/39 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/40<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/40 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/41<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/41 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/42<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/42 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/43<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/43 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/44<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/44 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/45<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/45 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/46<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/46 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/47<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/47 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/48<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/48 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/49<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/49 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/50<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/50 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/51<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/51 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/52<br / [...]

2019-08-30 07:09 UTC, FochQu commented
test linux build danger

2019-08-30 07:12 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-08-30 07:17 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-30 07:30 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Residual</em><br />
[==========] Running 162 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 132 tests from ResidualKernel/ResidualTest<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/0<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/0 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/1<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/1 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/2<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/2 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/3<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/3 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/4<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/4 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/5<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/5 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/6<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/6 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/7<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/7 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/8<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/8 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/9<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/9 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/10<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/10 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/11<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/11 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/12<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/12 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/13<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/13 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/14<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/14 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/15<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/15 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/16<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/16 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/17<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/17 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/18<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/18 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/19<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/19 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/20<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/20 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/21<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/21 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/22<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/22 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/23<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/23 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/24<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/24 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/25<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/25 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/26<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/26 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/27<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/27 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/28<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/28 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/29<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/29 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/30<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/30 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/31<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/31 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/32<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/32 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/33<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/33 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/34<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/34 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/35<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/35 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/36<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/36 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/37<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/37 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/38<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/38 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/39<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/39 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/40<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/40 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/41<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/41 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/42<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/42 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/43<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/43 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/44<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/44 (1 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/45<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/45 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/46<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/46 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/47<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/47 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/48<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/48 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/49<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/49 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/50<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/50 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/51<br />
[       OK ] ResidualKernel/ResidualTest.ResidualTest/51 (0 ms)<br />
[ RUN      ] ResidualKernel/ResidualTest.ResidualTest/52<br / [...]

2019-08-31 11:15 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-31 22:50 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-03 01:53 UTC, FochQu commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Residual*

2019-09-10 01:29 UTC, Cidana-Developers commented
Can one of the admins verify this patch?

2019-09-10 05:37 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `Source/Lib/Common/Codec/EbPictureOperators.c`

* `Source/Lib/Common/Codec/EbPictureOperators.h`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### Source/Lib/Common/Codec/EbPictureOperators.c
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.c
+++ Source/Lib/Common/Codec/EbPictureOperators.c
@@ -224,58 +224,53 @@
     return;
 }
 
-void residual_kernel_subsampled(
-    uint8_t   *input,
-    uint32_t   input_stride,
-    uint8_t   *pred,
-    uint32_t   pred_stride,
-    int16_t  *residual,
-    uint32_t   residual_stride,
-    uint32_t   area_width,
-    uint32_t   area_height,
-    uint8_t    last_line)
-{
-    uint32_t  column_index;
-    uint32_t  row_index = 0;
-
-    uint8_t   *input_O = input;
-    uint8_t   *pred_O = pred;
-    int16_t  *residual_O = residual;
-
-
-    //hard code subampling dimensions, keep residual_stride
-    area_height >>= 1;
-    input_stride <<= 1;
-    pred_stride <<= 1;
-
-
-    while (row_index < area_height) {
-        column_index = 0;
-        while (column_index < area_width) {
-            residual[column_index] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            residual[column_index + residual_stride] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            ++column_index;
-        }
-
-        input += input_stride;
-        pred += pred_stride;
-        residual += (residual_stride << 1);
-        ++row_index;
+void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                uint8_t *pred, uint32_t pred_stride,
+                                int16_t *residual, uint32_t residual_stride,
+                                uint32_t area_width, uint32_t area_height,
+                                uint8_t last_line) {
+  uint32_t column_index;
+  uint32_t row_index = 0;
+
+  uint8_t *input_O = input;
+  uint8_t *pred_O = pred;
+  int16_t *residual_O = residual;
+
+  // hard code subampling dimensions, keep residual_stride
+  area_height >>= 1;
+  input_stride <<= 1;
+  pred_stride <<= 1;
+
+  while (row_index < area_height) {
+    column_index = 0;
+    while (column_index < area_width) {
+      residual[column_index] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      residual[column_index + residual_stride] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      ++column_index;
     }
 
-    //do the last line:
-    if (last_line) {
-        input_stride = input_stride / 2;
-        pred_stride = pred_stride / 2;
-        area_height = area_height * 2;
-        column_index = 0;
-        while (column_index < area_width) {
-            residual_O[(area_height - 1)*residual_stride + column_index] = ((int16_t)input_O[(area_height - 1)*input_stride + column_index]) - ((int16_t)pred_O[(area_height - 1)*pred_stride + column_index]);
-            ++column_index;
-        }
-
+    input += input_stride;
+    pred += pred_stride;
+    residual += (residual_stride << 1);
+    ++row_index;
+  }
+
+  // do the last line:
+  if (last_line) {
+    input_stride = input_stride / 2;
+    pred_stride = pred_stride / 2;
+    area_height = area_height * 2;
+    column_index = 0;
+    while (column_index < area_width) {
+      residual_O[(area_height - 1) * residual_stride + column_index] =
+          ((int16_t)input_O[(area_height - 1) * input_stride + column_index]) -
+          ((int16_t)pred_O[(area_height - 1) * pred_stride + column_index]);
+      ++column_index;
     }
-    return;
+  }
+  return;
 }
 
 uint64_t ComputeNxMSatd8x8Units_U8(

``` 

#### Source/Lib/Common/Codec/EbPictureOperators.h
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.h
+++ Source/Lib/Common/Codec/EbPictureOperators.h
@@ -378,16 +378,11 @@
         uint32_t  area_width,
         uint32_t  area_height);
 
-    void residual_kernel_subsampled(
-        uint8_t   *input,
-        uint32_t   input_stride,
-        uint8_t   *pred,
-        uint32_t   pred_stride,
-        int16_t  *residual,
-        uint32_t   residual_stride,
-        uint32_t   area_width,
-        uint32_t   area_height,
-        uint8_t    last_line);
+    void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                    uint8_t *pred, uint32_t pred_stride,
+                                    int16_t *residual, uint32_t residual_stride,
+                                    uint32_t area_width, uint32_t area_height,
+                                    uint8_t last_line);
 
     static EbZeroCoeffType FUNC_TABLE pic_zero_out_coef_func_ptr_array[ASM_TYPE_TOTAL][5] = {
         // NON_AVX2

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 05:43 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 05:44 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 10:14 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `Source/Lib/Common/Codec/EbPictureOperators.c`

* `Source/Lib/Common/Codec/EbPictureOperators.h`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### Source/Lib/Common/Codec/EbPictureOperators.c
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.c
+++ Source/Lib/Common/Codec/EbPictureOperators.c
@@ -224,58 +224,53 @@
     return;
 }
 
-void residual_kernel_subsampled(
-    uint8_t   *input,
-    uint32_t   input_stride,
-    uint8_t   *pred,
-    uint32_t   pred_stride,
-    int16_t  *residual,
-    uint32_t   residual_stride,
-    uint32_t   area_width,
-    uint32_t   area_height,
-    uint8_t    last_line)
-{
-    uint32_t  column_index;
-    uint32_t  row_index = 0;
-
-    uint8_t   *input_O = input;
-    uint8_t   *pred_O = pred;
-    int16_t  *residual_O = residual;
-
-
-    //hard code subampling dimensions, keep residual_stride
-    area_height >>= 1;
-    input_stride <<= 1;
-    pred_stride <<= 1;
-
-
-    while (row_index < area_height) {
-        column_index = 0;
-        while (column_index < area_width) {
-            residual[column_index] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            residual[column_index + residual_stride] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            ++column_index;
-        }
-
-        input += input_stride;
-        pred += pred_stride;
-        residual += (residual_stride << 1);
-        ++row_index;
+void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                uint8_t *pred, uint32_t pred_stride,
+                                int16_t *residual, uint32_t residual_stride,
+                                uint32_t area_width, uint32_t area_height,
+                                uint8_t last_line) {
+  uint32_t column_index;
+  uint32_t row_index = 0;
+
+  uint8_t *input_O = input;
+  uint8_t *pred_O = pred;
+  int16_t *residual_O = residual;
+
+  // hard code subampling dimensions, keep residual_stride
+  area_height >>= 1;
+  input_stride <<= 1;
+  pred_stride <<= 1;
+
+  while (row_index < area_height) {
+    column_index = 0;
+    while (column_index < area_width) {
+      residual[column_index] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      residual[column_index + residual_stride] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      ++column_index;
     }
 
-    //do the last line:
-    if (last_line) {
-        input_stride = input_stride / 2;
-        pred_stride = pred_stride / 2;
-        area_height = area_height * 2;
-        column_index = 0;
-        while (column_index < area_width) {
-            residual_O[(area_height - 1)*residual_stride + column_index] = ((int16_t)input_O[(area_height - 1)*input_stride + column_index]) - ((int16_t)pred_O[(area_height - 1)*pred_stride + column_index]);
-            ++column_index;
-        }
-
+    input += input_stride;
+    pred += pred_stride;
+    residual += (residual_stride << 1);
+    ++row_index;
+  }
+
+  // do the last line:
+  if (last_line) {
+    input_stride = input_stride / 2;
+    pred_stride = pred_stride / 2;
+    area_height = area_height * 2;
+    column_index = 0;
+    while (column_index < area_width) {
+      residual_O[(area_height - 1) * residual_stride + column_index] =
+          ((int16_t)input_O[(area_height - 1) * input_stride + column_index]) -
+          ((int16_t)pred_O[(area_height - 1) * pred_stride + column_index]);
+      ++column_index;
     }
-    return;
+  }
+  return;
 }
 
 uint64_t ComputeNxMSatd8x8Units_U8(

``` 

#### Source/Lib/Common/Codec/EbPictureOperators.h
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.h
+++ Source/Lib/Common/Codec/EbPictureOperators.h
@@ -378,16 +378,11 @@
         uint32_t  area_width,
         uint32_t  area_height);
 
-    void residual_kernel_subsampled(
-        uint8_t   *input,
-        uint32_t   input_stride,
-        uint8_t   *pred,
-        uint32_t   pred_stride,
-        int16_t  *residual,
-        uint32_t   residual_stride,
-        uint32_t   area_width,
-        uint32_t   area_height,
-        uint8_t    last_line);
+    void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                    uint8_t *pred, uint32_t pred_stride,
+                                    int16_t *residual, uint32_t residual_stride,
+                                    uint32_t area_width, uint32_t area_height,
+                                    uint8_t last_line);
 
     static EbZeroCoeffType FUNC_TABLE pic_zero_out_coef_func_ptr_array[ASM_TYPE_TOTAL][5] = {
         // NON_AVX2

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 11:09 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 11:15 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 02:03 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `Source/Lib/Common/Codec/EbPictureOperators.c`

* `Source/Lib/Common/Codec/EbPictureOperators.h`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### Source/Lib/Common/Codec/EbPictureOperators.c
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.c
+++ Source/Lib/Common/Codec/EbPictureOperators.c
@@ -224,58 +224,53 @@
     return;
 }
 
-void residual_kernel_subsampled(
-    uint8_t   *input,
-    uint32_t   input_stride,
-    uint8_t   *pred,
-    uint32_t   pred_stride,
-    int16_t  *residual,
-    uint32_t   residual_stride,
-    uint32_t   area_width,
-    uint32_t   area_height,
-    uint8_t    last_line)
-{
-    uint32_t  column_index;
-    uint32_t  row_index = 0;
-
-    uint8_t   *input_O = input;
-    uint8_t   *pred_O = pred;
-    int16_t  *residual_O = residual;
-
-
-    //hard code subampling dimensions, keep residual_stride
-    area_height >>= 1;
-    input_stride <<= 1;
-    pred_stride <<= 1;
-
-
-    while (row_index < area_height) {
-        column_index = 0;
-        while (column_index < area_width) {
-            residual[column_index] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            residual[column_index + residual_stride] = ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
-            ++column_index;
-        }
-
-        input += input_stride;
-        pred += pred_stride;
-        residual += (residual_stride << 1);
-        ++row_index;
+void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                uint8_t *pred, uint32_t pred_stride,
+                                int16_t *residual, uint32_t residual_stride,
+                                uint32_t area_width, uint32_t area_height,
+                                uint8_t last_line) {
+  uint32_t column_index;
+  uint32_t row_index = 0;
+
+  uint8_t *input_O = input;
+  uint8_t *pred_O = pred;
+  int16_t *residual_O = residual;
+
+  // hard code subampling dimensions, keep residual_stride
+  area_height >>= 1;
+  input_stride <<= 1;
+  pred_stride <<= 1;
+
+  while (row_index < area_height) {
+    column_index = 0;
+    while (column_index < area_width) {
+      residual[column_index] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      residual[column_index + residual_stride] =
+          ((int16_t)input[column_index]) - ((int16_t)pred[column_index]);
+      ++column_index;
     }
 
-    //do the last line:
-    if (last_line) {
-        input_stride = input_stride / 2;
-        pred_stride = pred_stride / 2;
-        area_height = area_height * 2;
-        column_index = 0;
-        while (column_index < area_width) {
-            residual_O[(area_height - 1)*residual_stride + column_index] = ((int16_t)input_O[(area_height - 1)*input_stride + column_index]) - ((int16_t)pred_O[(area_height - 1)*pred_stride + column_index]);
-            ++column_index;
-        }
-
+    input += input_stride;
+    pred += pred_stride;
+    residual += (residual_stride << 1);
+    ++row_index;
+  }
+
+  // do the last line:
+  if (last_line) {
+    input_stride = input_stride / 2;
+    pred_stride = pred_stride / 2;
+    area_height = area_height * 2;
+    column_index = 0;
+    while (column_index < area_width) {
+      residual_O[(area_height - 1) * residual_stride + column_index] =
+          ((int16_t)input_O[(area_height - 1) * input_stride + column_index]) -
+          ((int16_t)pred_O[(area_height - 1) * pred_stride + column_index]);
+      ++column_index;
     }
-    return;
+  }
+  return;
 }
 
 uint64_t ComputeNxMSatd8x8Units_U8(

``` 

#### Source/Lib/Common/Codec/EbPictureOperators.h
```diff 
--- Source/Lib/Common/Codec/EbPictureOperators.h
+++ Source/Lib/Common/Codec/EbPictureOperators.h
@@ -378,16 +378,11 @@
         uint32_t  area_width,
         uint32_t  area_height);
 
-    void residual_kernel_subsampled(
-        uint8_t   *input,
-        uint32_t   input_stride,
-        uint8_t   *pred,
-        uint32_t   pred_stride,
-        int16_t  *residual,
-        uint32_t   residual_stride,
-        uint32_t   area_width,
-        uint32_t   area_height,
-        uint8_t    last_line);
+    void residual_kernel_subsampled(uint8_t *input, uint32_t input_stride,
+                                    uint8_t *pred, uint32_t pred_stride,
+                                    int16_t *residual, uint32_t residual_stride,
+                                    uint32_t area_width, uint32_t area_height,
+                                    uint8_t last_line);
 
     static EbZeroCoeffType FUNC_TABLE pic_zero_out_coef_func_ptr_array[ASM_TYPE_TOTAL][5] = {
         // NON_AVX2

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 02:10 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 02:11 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-16 01:14 UTC, Cidana-Developers commented
merged, close it.

2019-09-16 01:14 UTC, closed without merging