Add picture addition test
Cidana-Developers/SVT-AV1 pull request #69
Opened 2019-08-27 08:55 UTC by ivy-zhang

1.add picture_addition_kernel{m}x{n}_{sse,sse2}_intrin test
2.add picture_addition_kernel{m}x{n}_av1_sse2_intrin test
3.add picture_addition_kernel16bit_sse2_intrin test

2019-08-27 08:56 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-08-29 05:27 UTC, ivy-zhang commented
# Add Picture addition test

## Comments
## warnings in Local build
1. linux:  ok
2. windows:  ok

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a.  linux: ok
3. appvedor
  a. no warnings

## Test Plan: 
  Run the unit test with `./SvtAv1UnitTest --gtest_filter="*PictureAddition*"`, and check the result

## dry run output
~~~
$ ./SvtAv1UnitTests.exe --gtest_filter="*PictureAddition*"
Running main() from C:\Users\Ryan\addPic\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = *PictureAddition*
[==========] Running 30 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 30 tests from PictureAddition/PictureAdditionTest
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (1 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (1 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (1 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (2 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (1 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (2 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (1 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (1 ms)
[----------] 30 tests from PictureAddition/PictureAdditionTest (44 ms total)

[----------] Global test environment tear-down
[==========] 30 tests from 1 test case ran. (53 ms total)
[  PASSED  ] 30 tests.


~~~

2019-08-30 01:47 UTC, Cidana-Developers commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-08-30 01:54 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 30 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (0 ms)<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest (2 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 30 tests from 1 test case ran. (2 ms total)<br />
[  PASSED  ] 30 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-30 02:41 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-08-30 02:50 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 30 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (0 ms)<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest (2 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 30 tests from 1 test case ran. (2 ms total)<br />
[  PASSED  ] 30 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 06:09 UTC, Cidana-Developers requested changes

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +    AreaSize areaSize;
rename areaSize to area_size

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +	void SetUp() {
add override attributes

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +	void SetUp() {
some format issue here.

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +               test_size_ * sizeof(recon116bit_[0]));
can we rename recon116bit to recon1_16bit?

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +        const int16_t mask = (1 << 8) - 1;
Is the mask correct? Should it changed to (1<<16) -1 ?

2019-09-09 06:09 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +        for (uint16_t j = 0; j < height; j++) {
chang the uint16_t to uint32_t.

2019-09-09 06:55 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +            memset(residual_,
do not use memset here.

2019-09-09 07:54 UTC, Cidana-Developers commented
Can one of the admins verify this patch?

2019-09-09 07:55 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-09 08:02 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 09:02 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 00:50 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-10 00:59 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 01:24 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-10 01:32 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 30 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (1 ms)<br />
[———-] 30 tests from PictureAddition/PictureAdditionTest (2 ms total)</p>

<p>[———-] Global test environment tear-down<br />
[==========] 30 tests from 1 test case ran. (2 ms total)<br />
[  PASSED  ] 30 tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:05 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-10 03:05 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/PictureAdditionTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/PictureAdditionTest.cc
```diff 
--- test/PictureAdditionTest.cc
+++ test/PictureAdditionTest.cc
@@ -191,7 +191,7 @@
         case ALL_RANDOM: {
             for (uint32_t i = 0; i < test_size_; i++) {
                 pred_[i] = rnd_uint8.random();
-				residual_[i] = residual_int32_[i] = rnd_int16.random();
+                residual_[i] = residual_int32_[i] = rnd_int16.random();
             }
             break;
         }
@@ -279,7 +279,7 @@
                        area_width_,
                        area_height_,
                        2);
-        
+
         printf("width: %d, height: %d,pattern: %d   \n",
                area_width_,
                area_height_,

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:12 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-10 03:13 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
width: 4, height: 4,pattern: 0   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
width: 4, height: 4,pattern: 1   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
width: 4, height: 4,pattern: 2   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
width: 4, height: 4,pattern: 3   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
width: 4, height: 4,pattern: 4   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
width: 8, height: 8,pattern: 0   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
width: 8, height: 8,pattern: 1   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
width: 8, height: 8,pattern: 2   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
width: 8, height: 8,pattern: 3   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
width: 8, height: 8,pattern: 4   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
width: 16, height: 16,pattern: 0   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
width: 16, height: 16,pattern: 1   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
width: 16, height: 16,pattern: 2   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
width: 16, height: 16,pattern: 3   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
width: 16, height: 16,pattern: 4   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
width: 32, height: 32,pattern: 0   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
width: 32, height: 32,pattern: 1   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
width: 32, height: 32,pattern: 2   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
width: 32, height: 32,pattern: 3   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19<br />
width: 32, height: 32,pattern: 4   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20<br />
width: 64, height: 64,pattern: 0   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21<br />
width: 64, height: 64,pattern: 1   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22<br />
width: 64, height: 64,pattern: 2   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23<br />
width: 64, height: 64,pattern: 3   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24<br />
width: 64, height: 64,pattern: 4   <br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ R [...]

2019-09-10 03:14 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:18 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:21 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18 (0 ms)<b [...]

2019-09-10 03:45 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:49 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 03:55 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 04:10 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-10 04:17 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18 (0 ms)<b [...]

2019-09-10 08:34 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 06:24 UTC, Cidana-Developers commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-11 06:26 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 06:30 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 06:31 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/19 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/20 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/21 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/22 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/23 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/24 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/3 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/6 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/8 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/13 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/14 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAddition16bitTest/18 (0 ms)<b [...]

2019-09-12 09:01 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-16 01:13 UTC, Cidana-Developers commented
merged, close it.

2019-09-16 01:13 UTC, closed without merging