Add Spatial Full Distortion Test
Cidana-Developers/SVT-AV1 pull request #73
Opened 2019-08-29 05:40 UTC by ivy-zhang

1.add spatial_full_distortion_kernel{4, 8, 16, 32, 64,
      128}x_n_{sse2,avx2}_intrin test
2. add spatial_full_distortion_kernel_{avx2,avx512} test

2019-08-29 05:42 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-08-29 05:47 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-29 05:51 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-08-29 05:59 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Spatial</em><br />
[==========] Running 100 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest<br />
[ RUN      ] AVX2/SpatialFullDistortionTest.CheckOutput/0<br />
[       OK ] AVX2/SpatialFullDistortionTest.CheckOutput/0 (8 ms)<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest (8 ms total)</p>

<p>[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (1 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (4 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (5 ms)<br />
[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (32 ms total)</p>

<p>[———-] 81 tests from SpatialKernelFunc/SpatialFullDistortionKernelFuncTest<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11 (7 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest [...]

2019-08-29 06:29 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-08-29 06:37 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Spatial</em><br />
[==========] Running 100 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest<br />
[ RUN      ] AVX2/SpatialFullDistortionTest.CheckOutput/0<br />
[       OK ] AVX2/SpatialFullDistortionTest.CheckOutput/0 (11 ms)<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest (11 ms total)</p>

<p>[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (1 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (8 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (5 ms)<br />
[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (35 ms total)</p>

<p>[———-] 81 tests from SpatialKernelFunc/SpatialFullDistortionKernelFuncTest<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5 (4 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8 (7 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17 (4 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTe [...]

2019-08-29 07:25 UTC, ivy-zhang commented
# Add Spatial Full Distortion test

## Comments
## warnings in Local build
1. linux:  ok
2. windows:  ok

## warnings on remote ci servers
1. jenkins:
a. clang-format
b. 
2. travis
  a.  linux: ok
3. appvedor
  a. no warnings

## Test Plan: 
  Run the unit test with `./SvtAv1UnitTest --gtest_filter="*Spatial*"`, and check the result

## dry run output
~~~
$ ./SvtAv1UnitTests.exe --gtest_filter="*Spatial*"
Running main() from C:\Users\Ryan\addadd\SVT-AV1\third_party\googletest\src\gtest_main.cc
Note: Google Test filter = *SpatialFunc*
[==========] Running 18 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (1 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (2 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (30 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (27 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (28 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (27 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (1 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (27 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (1 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (1 ms)
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (32 ms)
[----------] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (187 ms total)

[----------] Global test environment tear-down
[==========] 18 tests from 1 test case ran. (195 ms total)
[  PASSED  ] 18 tests.


~~~

2019-09-03 02:49 UTC, FochQu commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-09-03 03:10 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Spatial</em><br />
[==========] Running 100 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest<br />
[ RUN      ] AVX2/SpatialFullDistortionTest.CheckOutput/0<br />
[       OK ] AVX2/SpatialFullDistortionTest.CheckOutput/0 (10 ms)<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest (10 ms total)</p>

<p>[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (7 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (4 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (8 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (5 ms)<br />
[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (35 ms total)</p>

<p>[———-] 81 tests from SpatialKernelFunc/SpatialFullDistortionKernelFuncTest<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14 (7 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTe [...]

2019-09-09 06:02 UTC, Cidana-Developers requested changes
Some minor modification required.
By the way, we should discuss how to merge the code between non-avx512 and avx512.

2019-09-09 06:02 UTC, Cidana-Developers commented on test/SpatialFullDistortionTest.cc
> +    uint32_t areaWidth_, areaHeight_;
variable style? rename it to area_width or area_height

2019-09-09 06:02 UTC, Cidana-Developers commented on test/SpatialFullDistortionTest.cc
> +    AreaSize areaSize;
rename areaSize to area_size

2019-09-09 06:02 UTC, Cidana-Developers commented on test/SpatialFullDistortionTest.cc
> +            << "Compare avx22 vs c Spatial distortion result error";
typo? rename avx22 to avx2.

2019-09-09 07:37 UTC, Cidana-Developers commented
Can one of the admins verify this patch?

2019-09-09 07:39 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-09-09 07:46 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Spatial</em><br />
[==========] Running 100 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest<br />
[ RUN      ] AVX2/SpatialFullDistortionTest.CheckOutput/0<br />
[       OK ] AVX2/SpatialFullDistortionTest.CheckOutput/0 (8 ms)<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest (8 ms total)</p>

<p>[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (1 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (1 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (4 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (7 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (5 ms)<br />
[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (33 ms total)</p>

<p>[———-] 81 tests from SpatialKernelFunc/SpatialFullDistortionKernelFuncTest<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5 (4 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17 (4 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest [...]

2019-09-09 07:48 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 09:39 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-10 01:09 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*Spatial*

2019-09-10 01:16 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Running main() from /home/jenk...
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>Spatial</em><br />
[==========] Running 100 tests from 3 test cases.<br />
[———-] Global test environment set-up.<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest<br />
[ RUN      ] AVX2/SpatialFullDistortionTest.CheckOutput/0<br />
[       OK ] AVX2/SpatialFullDistortionTest.CheckOutput/0 (8 ms)<br />
[———-] 1 test from AVX2/SpatialFullDistortionTest (8 ms total)</p>

<p>[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/1 (1 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/2 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/5 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/8 (4 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/14 (6 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17<br />
[       OK ] SpatialFunc/SpatialFullDistortionFuncTest.SpatialFuncTest/17 (6 ms)<br />
[———-] 18 tests from SpatialFunc/SpatialFullDistortionFuncTest (33 ms total)</p>

<p>[———-] 81 tests from SpatialKernelFunc/SpatialFullDistortionKernelFuncTest<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/0 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/1 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/2 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/3 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/4 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/5 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/6 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/7 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/8 (6 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/9 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/10 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/11 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/12 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/13 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/14 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/15 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/16 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/17 (5 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18<br />
[       OK ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest.SpatialKernelFuncTest/18 (0 ms)<br />
[ RUN      ] SpatialKernelFunc/SpatialFullDistortionKernelFuncTest [...]

2019-09-11 05:39 UTC, Cidana-Developers commented
merged, close it.

2019-09-11 05:39 UTC, closed without merging