fix coding style
Cidana-Developers/SVT-AV1 pull request #76
Opened 2019-09-06 03:25 UTC by ivy-zhang

2019-09-06 03:25 UTC, Cidana-Developers commented
Can one of the admins verify this patch?

2019-09-06 03:46 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*AVCMCP*

2019-09-06 03:55 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
      <tr>
        <td>:warning:</td>
        <td>
        Danger found 1 violations with this PR. Due to GitHub's max issue comment size, the number shown has been truncated to 0.
        </td>
      </tr>
  </tbody>
</table>

### Tests: 

Name | Value_param | Status | Time | Classname|
--- | --- | --- | --- | ---|
AVCStyleMcpPUTest/0 | ((64, 64), 0) | run | 0.005 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/2 | ((64, 64), 2) | run | 0.31 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/3 | ((64, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/5 | ((64, 32), 2) | run | 0.362 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/6 | ((32, 64), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/8 | ((32, 64), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/9 | ((32, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/11 | ((32, 32), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/12 | ((32, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/14 | ((32, 16), 2) | run | 0.306 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/15 | ((16, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/17 | ((16, 32), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/18 | ((16, 16), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/20 | ((16, 16), 2) | run | 0.309 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/21 | ((16, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/23 | ((16, 8), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/24 | ((8, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/26 | ((8, 16), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/27 | ((8, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/29 | ((8, 8), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/30 | ((8, 4), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/33 | ((4, 4), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/36 | ((4, 8), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/39 | ((4, 16), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/42 | ((16, 4), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/45 | ((8, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/47 | ((8, 32), 2) | run | 0.302 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/48 | ((32, 8), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/50 | ((32, 8), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/51 | ((16, 64), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/53 | ((16, 64), 2) | run | 0.307 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/54 | ((64, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/56 | ((64, 16), 2) | run | 0.308 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/57 | ((24, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/59 | ((24, 24), 2) | run | 0.305 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/60 | ((24, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/62 | ((24, 16), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/63 | ((16, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/65 | ((16, 24), 2) | run | 0.302 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/66 | ((24, 8), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/68 | ((24, 8), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/69 | ((8, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/71 | ((8, 24), 2) | run | 0.347 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/72 | ((64, 24), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/74 | ((64, 24), 2) | run | 0.309 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/75 | ((48, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/77 | ((48, 24), 2) | run | 0.312 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/78 | ((32, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/80 | ((32, 24), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/81 | ((24, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/83 | ((24, 32), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/84 | ((48, 48), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/86 | ((48, 48), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/87 | ((48, 16), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/89 | ((48, 16), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/90 | ((48, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/92 | ((48, 32), 2) | run | 0.307 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/93 | ((16, 48), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/95 | ((16, 48), 2) | run | 0.306 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/96 | ((32, 48), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/98 | ((32, 48), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/99 | ((48, 64), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/101 | ((48, 64), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/102 | ((64, 48), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/104 | ((64, 48), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpSearchRegionTest/0 | ((64, 64), 0) | run | 0.004 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/1 | ((64, 64), 1) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/2 | ((64, 64), 2) | run | 0.306 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/3 | ((64, 32), 0) | run | 0.002 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/4 | ((64, 32), 1) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/5 | ((64, 32), 2) | run | 0.305 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/6 | ((48, 16), 0) | run | 0.002 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/8 | ((48, 16), 2) | run | 0.304 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/9 | ((16, 10), 0) | run | 0.001 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/11 | ((16, 10), 2) | run | 0.303 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/12 | ((112, 112), 0) | run | 0.006 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/13 | ((112, 112), 1) | run | 0.004 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/14 | ((112, 112), 2) | run | 0.307 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/15 | ((128, 128), 0) | run | 0.006 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/16 | ((128, 128), 1) | run | 0.006 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/17 | ((128, 128), 2) | run | 0.308 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSea [...]

2019-09-09 02:43 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 02:43 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 03:09 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*AVCMCP*

2019-09-09 03:20 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
      <tr>
        <td>:warning:</td>
        <td>
        Danger found 1 violations with this PR. Due to GitHub's max issue comment size, the number shown has been truncated to 0.
        </td>
      </tr>
  </tbody>
</table>

### Tests: 

Name | Value_param | Status | Time | Classname|
--- | --- | --- | --- | ---|
AVCStyleMcpPUTest/0 | ((64, 64), 0) | run | 0.007 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/2 | ((64, 64), 2) | run | 0.335 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/3 | ((64, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/5 | ((64, 32), 2) | run | 0.358 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/6 | ((32, 64), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/8 | ((32, 64), 2) | run | 0.322 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/9 | ((32, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/11 | ((32, 32), 2) | run | 0.307 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/12 | ((32, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/14 | ((32, 16), 2) | run | 0.311 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/15 | ((16, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/17 | ((16, 32), 2) | run | 0.305 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/18 | ((16, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/20 | ((16, 16), 2) | run | 0.305 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/21 | ((16, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/23 | ((16, 8), 2) | run | 0.307 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/24 | ((8, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/26 | ((8, 16), 2) | run | 0.306 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/27 | ((8, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/29 | ((8, 8), 2) | run | 0.302 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/30 | ((8, 4), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/33 | ((4, 4), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/36 | ((4, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/39 | ((4, 16), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/42 | ((16, 4), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/45 | ((8, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/47 | ((8, 32), 2) | run | 0.308 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/48 | ((32, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/50 | ((32, 8), 2) | run | 0.309 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/51 | ((16, 64), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/53 | ((16, 64), 2) | run | 0.306 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/54 | ((64, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/56 | ((64, 16), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/57 | ((24, 24), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/59 | ((24, 24), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/60 | ((24, 16), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/62 | ((24, 16), 2) | run | 0.305 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/63 | ((16, 24), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/65 | ((16, 24), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/66 | ((24, 8), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/68 | ((24, 8), 2) | run | 0.302 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/69 | ((8, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/71 | ((8, 24), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/72 | ((64, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/74 | ((64, 24), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/75 | ((48, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/77 | ((48, 24), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/78 | ((32, 24), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/80 | ((32, 24), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/81 | ((24, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/83 | ((24, 32), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/84 | ((48, 48), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/86 | ((48, 48), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/87 | ((48, 16), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/89 | ((48, 16), 2) | run | 0.304 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/90 | ((48, 32), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/92 | ((48, 32), 2) | run | 0.306 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/93 | ((16, 48), 0) | run | 0.001 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/95 | ((16, 48), 2) | run | 0.302 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/96 | ((32, 48), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/98 | ((32, 48), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/99 | ((48, 64), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/101 | ((48, 64), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/102 | ((64, 48), 0) | run | 0.002 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpPUTest/104 | ((64, 48), 2) | run | 0.303 | AVCMCPPU/AVCStyleMcpPUTest|
AVCStyleMcpSearchRegionTest/0 | ((64, 64), 0) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/1 | ((64, 64), 1) | run | 0.002 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/2 | ((64, 64), 2) | run | 0.307 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/3 | ((64, 32), 0) | run | 0.002 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/4 | ((64, 32), 1) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/5 | ((64, 32), 2) | run | 0.307 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/6 | ((48, 16), 0) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/8 | ((48, 16), 2) | run | 0.311 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/9 | ((16, 10), 0) | run | 0.003 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/11 | ((16, 10), 2) | run | 0.307 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/12 | ((112, 112), 0) | run | 0.004 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/13 | ((112, 112), 1) | run | 0.005 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/14 | ((112, 112), 2) | run | 0.309 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/15 | ((128, 128), 0) | run | 0.006 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/16 | ((128, 128), 1) | run | 0.008 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSearchRegionTest/17 | ((128, 128), 2) | run | 0.315 | AVCMCPSearchRegion/AVCStyleMcpSearchRegionTest|
AVCStyleMcpSe [...]

2019-09-09 03:58 UTC, Cidana-Developers requested changes

2019-09-09 03:58 UTC, Cidana-Developers commented on test/AVCStyleMcpTest.cc
> +        dst_size_ = 2 * block_size_;
Why double the dst_size_?

2019-09-09 03:58 UTC, Cidana-Developers commented on Source/Lib/Common/Codec/EbAvcStyleMcp.h
>                                             uint32_t puWidth, uint32_t puHeight,
Could you also modify the style of the variables, like change dstStride to dst_stride?

2019-09-09 03:58 UTC, Cidana-Developers commented on Source/Lib/Common/Codec/EbAvcStyleMcp.c
> +  int16_t weight = 1;
Are they const? if it is, add const before declaration.

2019-09-09 06:43 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: 

  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">
</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-09 08:12 UTC, Cidana-Developers approved these changes

2019-09-11 02:43 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c`

* `Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h`

* `Source/Lib/Common/Codec/EbAvcStyleMcp.c`

* `Source/Lib/Common/Codec/EbAvcStyleMcp.h`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
```diff 
--- Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
+++ Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.c
@@ -9,26 +9,20 @@
 /*********************************
 * Picture Average
 *********************************/
-void picture_average_kernel(
-    EbByte   src0,
-    uint32_t   src0_stride,
-    EbByte   src1,
-    uint32_t   src1_stride,
-    EbByte   dst,
-    uint32_t   dst_stride,
-    uint32_t   area_width,
-    uint32_t   area_height)
-{
-    uint32_t x, y;
+void picture_average_kernel(EbByte src0, uint32_t src0_stride, EbByte src1,
+                            uint32_t src1_stride, EbByte dst,
+                            uint32_t dst_stride, uint32_t area_width,
+                            uint32_t area_height) {
+  uint32_t x, y;
 
-    for (y = 0; y < area_height; y++) {
-        for (x = 0; x < area_width; x++) {
-            dst[x] = (src0[x] + src1[x] + 1) >> 1;
-        }
-        src0 += src0_stride;
-        src1 += src1_stride;
-        dst += dst_stride;
+  for (y = 0; y < area_height; y++) {
+    for (x = 0; x < area_width; x++) {
+      dst[x] = (src0[x] + src1[x] + 1) >> 1;
     }
+    src0 += src0_stride;
+    src1 += src1_stride;
+    dst += dst_stride;
+  }
 }
 
 /*********************************

``` 

#### Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
```diff 
--- Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
+++ Source/Lib/Common/C_DEFAULT/EbPictureOperators_C.h
@@ -10,45 +10,28 @@
 extern "C" {
 #endif
 
-    void picture_average_kernel(
-        EbByte   src0,
-        uint32_t   src0_stride,
-        EbByte   src1,
-        uint32_t   src1_stride,
-        EbByte   dst,
-        uint32_t   dst_stride,
-        uint32_t   area_width,
-        uint32_t   area_height);
+void picture_average_kernel(EbByte src0, uint32_t src0_stride, EbByte src1,
+                            uint32_t src1_stride, EbByte dst,
+                            uint32_t dst_stride, uint32_t area_width,
+                            uint32_t area_height);
 
-    void picture_copy_kernel(
-        EbByte   src,
-        uint32_t src_stride,
-        EbByte   dst,
-        uint32_t dst_stride,
-        uint32_t area_width,
-        uint32_t area_height,
-        uint32_t bytes_per_sample);
+void picture_copy_kernel(EbByte src, uint32_t src_stride, EbByte dst,
+                         uint32_t dst_stride, uint32_t area_width,
+                         uint32_t area_height, uint32_t bytes_per_sample);
 
-    uint64_t spatial_full_distortion_kernel_c(
-        uint8_t *input,
-        uint32_t input_offset,
-        uint32_t input_stride,
-        uint8_t *recon,
-        uint32_t recon_offset,
-        uint32_t recon_stride,
-        uint32_t area_width,
-        uint32_t area_height);
+uint64_t spatial_full_distortion_kernel_c(uint8_t *input, uint32_t input_offset,
+                                          uint32_t input_stride, uint8_t *recon,
+                                          uint32_t recon_offset,
+                                          uint32_t recon_stride,
+                                          uint32_t area_width,
+                                          uint32_t area_height);
 
-    extern void picture_addition_kernel(
-        uint8_t *pred_ptr,
-        uint32_t pred_stride,
-        int32_t *residual_ptr,
-        uint32_t residual_stride,
-        uint8_t *recon_ptr,
-        uint32_t recon_stride,
-        uint32_t width,
-        uint32_t height,
-        int32_t  bd);
+extern void picture_addition_kernel(uint8_t *pred_ptr, uint32_t pred_stride,
+                                    int32_t *residual_ptr,
+                                    uint32_t residual_stride,
+                                    uint8_t *recon_ptr, uint32_t recon_stride,
+                                    uint32_t width, uint32_t height,
+                                    int32_t bd);
 
 #ifdef __cplusplus
 }

``` 

#### Source/Lib/Common/Codec/EbAvcStyleMcp.c
```diff 
--- Source/Lib/Common/Codec/EbAvcStyleMcp.c
+++ Source/Lib/Common/Codec/EbAvcStyleMcp.c
@@ -50,7 +50,8 @@
 
   (void)temp_buf;
   (void)frac_pos;
-  picture_copy_kernel(ref_pic, src_stride, dst, dst_stride, pu_width, pu_height, 1);
+  picture_copy_kernel(ref_pic, src_stride, dst, dst_stride, pu_width, pu_height,
+                      1);
 
   for (row_idx = 0; row_idx < pu_height; ++row_idx) {
     for (column_idx = 0; column_idx < pu_width; ++column_idx) {
@@ -1150,134 +1151,127 @@
   }
 }
 
-void avc_style_luma_interpolation_filter_pose(EbByte ref_pic, uint32_t src_stride,
-                                           EbByte dst, uint32_t dst_stride,
-                                           uint32_t pu_width, uint32_t pu_height,
-                                           EbByte temp_buf, uint32_t frac_pos) {
+void avc_style_luma_interpolation_filter_pose(
+    EbByte ref_pic, uint32_t src_stride, EbByte dst, uint32_t dst_stride,
+    uint32_t pu_width, uint32_t pu_height, EbByte temp_buf, uint32_t frac_pos) {
   uint32_t temp_buf_size = pu_width * pu_height;
   (void)frac_pos;
   avc_style_luma_interpolation_filter_horizontal(
       ref_pic, src_stride, temp_buf, pu_width, pu_width, pu_height, 0, 2);
   avc_style_luma_interpolation_filter_vertical(
-      ref_pic, src_stride, temp_buf + temp_buf_size, pu_width, pu_width, pu_height, 0,
-      2);
-  picture_average_kernel(temp_buf, pu_width, temp_buf + temp_buf_size, pu_width, dst,
-                       dst_stride, pu_width, pu_height);
+      ref_pic, src_stride, temp_buf + temp_buf_size, pu_width, pu_width,
+      pu_height, 0, 2);
+  picture_average_kernel(temp_buf, pu_width, temp_buf + temp_buf_size, pu_width,
+                         dst, dst_stride, pu_width, pu_height);
 }
 
-void avc_style_luma_interpolation_filter_posf(EbByte ref_pic, uint32_t src_stride,
-                                           EbByte dst, uint32_t dst_stride,
-                                           uint32_t pu_width, uint32_t pu_height,
-                                           EbByte temp_buf, uint32_t frac_pos) {
+void avc_style_luma_interpolation_filter_posf(
+    EbByte ref_pic, uint32_t src_stride, EbByte dst, uint32_t dst_stride,
+    uint32_t pu_width, uint32_t pu_height, EbByte temp_buf, uint32_t frac_pos) {
   uint32_t temp_buf_size = pu_width * pu_height;
   (void)frac_pos;
   avc_style_luma_interpolation_filter_horizontal(
       ref_pic, src_stride, temp_buf, pu_width, pu_width, pu_height, 0, 2);
   avc_style_luma_interpolation_filter_posj(
-      ref_pic, src_stride, temp_buf + temp_buf_size, pu_width, pu_width, pu_height,
-      temp_buf + 2 * temp_buf_size, 2);
-  picture_average_kernel(temp_buf, pu_width, temp_buf + temp_buf_size, pu_width, dst,
-                       dst_stride, pu_width, pu_height);
+      ref_pic, src_stride, temp_buf + temp_buf_size, pu_width, pu_width,
+      pu_height, temp_buf + 2 * temp_buf_size, 2);
+  picture_average_kernel(temp_buf, pu_width, temp_buf + temp_buf_size, pu_width,
+                         dst, dst_stride, pu_width, pu_height);
 }
 
-void avc_style_luma_in [...]

2019-09-11 02:51 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-11 02:53 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  0 Messages
  1 Markdown
-->

## Danger has errored
[!] Invalid `Dangerfile` file: undefined method `nodes` for nil:NilClass
```
 #  from Dangerfile:1
 #  -------------------------------------------
 >  junit.parse "dryruntest-report.xml"
 #  junit.report
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-25 02:22 UTC, Cidana-Developers commented
merged, close it.

2019-09-25 02:22 UTC, closed without merging