Add c
Cidana-Developers/SVT-AV1 pull request #78
Opened 2019-09-12 05:27 UTC by ivy-zhang

2019-09-12 05:27 UTC, Cidana-Developers commented
Can one of the admins verify this patch?

2019-09-12 05:29 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/PictureAdditionTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/PictureAdditionTest.cc
```diff 
--- test/PictureAdditionTest.cc
+++ test/PictureAdditionTest.cc
@@ -254,7 +254,8 @@
         }
     }
 
-    void check_output(uint32_t width, uint32_t height,uint8_t *out_1,uint8_t *out_2) {
+    void check_output(uint32_t width, uint32_t height, uint8_t *out_1,
+                      uint8_t *out_2) {
         int fail_count = 0;
         for (uint32_t j = 0; j < height; j++) {
             for (uint32_t k = 0; k < width; k++) {
@@ -310,7 +311,7 @@
                                 area_width_,
                                 area_height_,
                                 8);
-        check_output(area_width_, area_height_,recon1_,recon3_);
+        check_output(area_width_, area_height_, recon1_, recon3_);
         check_output(area_width_, area_height_, recon2_, recon3_);
         EXPECT_FALSE(HasFailure());
     }
@@ -341,7 +342,7 @@
     TestPattern test_pattern_;
     uint32_t area_width_, area_height_;
     uint32_t recon_stride_, pred_stride_, residual_stride_;
-    uint8_t *pred_, *recon1_, *recon2_,*recon3_;
+    uint8_t *pred_, *recon1_, *recon2_, *recon3_;
     uint16_t *recon1_16bit_, *recon2_16bit_, *pred16bit_;
     int16_t *residual_;
     int32_t *residual_int32_;

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 05:30 UTC, Cidana-Developers commented
<!--
  1 Error: Code style violations detected...
  0 Warnings
  0 Messages
  3 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code style violations detected.</td>
    </tr>
  </tbody>
</table>

### Code Style Check

---

Code style violations detected in the following files:
* `test/PictureAdditionTest.cc`

Execute one of the following actions and commit again:
1. Run `clang-format` on the offending files
2. Apply the suggested patches with `git apply patch`.

#### test/PictureAdditionTest.cc
```diff 
--- test/PictureAdditionTest.cc
+++ test/PictureAdditionTest.cc
@@ -254,7 +254,8 @@
         }
     }
 
-    void check_output(uint32_t width, uint32_t height,uint8_t *out_1,uint8_t *out_2) {
+    void check_output(uint32_t width, uint32_t height, uint8_t *out_1,
+                      uint8_t *out_2) {
         int fail_count = 0;
         for (uint32_t j = 0; j < height; j++) {
             for (uint32_t k = 0; k < width; k++) {
@@ -310,7 +311,7 @@
                                 area_width_,
                                 area_height_,
                                 8);
-        check_output(area_width_, area_height_,recon1_,recon3_);
+        check_output(area_width_, area_height_, recon1_, recon3_);
         check_output(area_width_, area_height_, recon2_, recon3_);
         EXPECT_FALSE(HasFailure());
     }
@@ -341,7 +342,7 @@
     TestPattern test_pattern_;
     uint32_t area_width_, area_height_;
     uint32_t recon_stride_, pred_stride_, residual_stride_;
-    uint8_t *pred_, *recon1_, *recon2_,*recon3_;
+    uint8_t *pred_, *recon1_, *recon2_, *recon3_;
     uint16_t *recon1_16bit_, *recon2_16bit_, *pred16bit_;
     int16_t *residual_;
     int32_t *residual_int32_;

``` 


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 05:33 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-12 05:39 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 05:41 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 05:49 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 05:50 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3, where GetParam() = (24-byte object &lt;04-00 00-00 04-00 00-00 70-08 BE-97 21-56 00-00 90-9D C6-97 21-56 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8, where GetParam() = (24-byte object &lt;08-00 00-00 08-00 00-00 00-09 BE-97 21-56 00-00 40-9E C6-97 21-56 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-0A BE-97 21-56 00-00 C0-9E C6-97 21-56 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-0A BE-97 21-56 00-00 C0-9E C6-97 21-56 00-00&gt;, 4) (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Ex [...]

2019-09-12 06:47 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +        check_output(area_width_, area_height_,recon1_,recon3_);
Could you rename recon3_ to recon_c_ to be more clear?

2019-09-12 06:50 UTC, Cidana-Developers requested changes

2019-09-12 06:50 UTC, Cidana-Developers commented on test/PictureAdditionTest.cc
> +        recon1_ = recon2_ = recon3_ = nullptr;
Suggest to rename recon3_ to recon_c_

2019-09-12 07:11 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-12 07:19 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 07:22 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3, where GetParam() = (24-byte object &lt;04-00 00-00 04-00 00-00 70-28 0E-2A 9C-55 00-00 90-BD 16-2A 9C-55 00-00&gt;, 3) (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8, where GetParam() = (24-byte object &lt;08-00 00-00 08-00 00-00 00-29 0E-2A 9C-55 00-00 40-BE 16-2A 9C-55 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-2A 0E-2A 9C-55 00-00 C0-BE 16-2A 9C-55 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-2A 0E-2A 9C-55 00-00 C0-BE 16-2A 9C-55 00-00&gt;, 4) (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Ex [...]

2019-09-12 07:44 UTC, ivy-zhang commented
dry_run_test @./Bin/Release/SvtAv1UnitTests --gtest_filter=*PictureAddition*

2019-09-12 07:56 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-12 07:56 UTC, Cidana-Developers commented
<!--
  1 Error: Tests have failed, see below f...
  0 Warnings
  1 Message: Running main() from /home/jenk...
  1 Markdown
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Running main() from /home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/third_party/googletest/src/gtest_main.cc<br />
Note: Google Test filter = <em>PictureAddition</em><br />
[==========] Running 50 tests from 1 test case.<br />
[———-] Global test environment set-up.<br />
[———-] 50 tests from PictureAddition/PictureAdditionTest<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/0 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/1 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/2 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 16<br />
compare picture addition result errorin test area for 16times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/3, where GetParam() = (24-byte object &lt;04-00 00-00 04-00 00-00 70-18 D4-69 8F-55 00-00 90-AD DC-69 8F-55 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/4 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/5 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/6 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/7 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 64<br />
compare picture addition result errorin test area for 64times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/8, where GetParam() = (24-byte object &lt;08-00 00-00 08-00 00-00 00-19 D4-69 8F-55 00-00 40-AE DC-69 8F-55 00-00&gt;, 3) (1 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/9 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/10 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/11 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/12 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 256<br />
compare picture addition result errorin test area for 256times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/13, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-1A D4-69 8F-55 00-00 C0-AE DC-69 8F-55 00-00&gt;, 3) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 2<br />
compare picture addition result errorin test area for 2times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Expected: false<br />
[  FAILED  ] PictureAddition/PictureAdditionTest.PictureAdditionTest/14, where GetParam() = (24-byte object &lt;10-00 00-00 10-00 00-00 40-1A D4-69 8F-55 00-00 C0-AE DC-69 8F-55 00-00&gt;, 4) (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/15 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/16 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17<br />
[       OK ] PictureAddition/PictureAdditionTest.PictureAdditionTest/17 (0 ms)<br />
[ RUN      ] PictureAddition/PictureAdditionTest.PictureAdditionTest/18<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:267: Failure<br />
Expected equality of these values:<br />
  0<br />
  fail_count<br />
    Which is: 1024<br />
compare picture addition result errorin test area for 1024times<br />
/home/jenkins/workspace/SVTAV1-Linux-GCC-Dry-Run-Test/test/PictureAdditionTest.cc:316: Failure<br />
Value of: HasFailure()<br />
  Actual: true<br />
Ex [...]

2019-09-12 08:51 UTC, Cidana-Developers commented
<!--
  0 Errors
  0 Warnings
  1 Message: Linux GCC Build PASS
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Linux GCC Build PASS</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-09-16 01:12 UTC, Cidana-Developers commented
merged, close it.

2019-09-16 01:12 UTC, closed without merging